### ISSUE TITLE
main: tsc broken by #5482/#5473 semantic merge conflict in useDialogFocusTrap (reds frontend/E2E/builds on every PR)

### ISSUE THREAD

**Issue by chenmingwei23** [kirodotdev/KiroCrew#5516]
## What broke

`main` fails frontend type check since 978c21e41 (#5473, merged 06:32 UTC):

```
src/hooks/useDialogFocusTrap.ts(85,14): error TS2552: Cannot find name 'imeLatchRef'. Did you mean 'imeLatch'?
```

This reds **Frontend Lint & Type Check**, and downstream **E2E (stub ACP backend)**, **Build Desktop (both ubuntu variants)** and **Build Wheel** on every PR merge ref (first seen on PR #5327's run at 06:43 UTC).

## Root cause: semantic merge conflict between two IME PRs

- #5482 (merged 05:03 UTC) added the Escape claim in `useDialogFocusTrap.ts` written against the then-current ref-based latch: `imeLatchRef.current!.claimKey(e)`.
- #5473 (merged 06:32 UTC) replaced that ref with the shared `useDocumentImeLatch` hook (`const imeLatch = useDocumentImeLatch(enabled)`), but its branch predates #5482's Escape branch, so the textual merge kept both: the new hook declaration and the old `imeLatchRef` reference.

Each PR was green on its own head; neither CI run saw the other's change.

## Fix

One line in `useDialogFocusTrap.ts:85`:

```ts
- if (!imeLatchRef.current!.claimKey(e)) return
+ if (!imeLatch.claimKey(e)) return
```

`useDocumentImeLatch` returns the same claim surface, so the Escape guard's semantics are unchanged.

**Comment by CrysisDeu** [comment]
🤖 Kiro Crew Auto-Pipeline [operator: CrysisDeu#0c98c3a2]: In-flight fixes already open — PR #5515, PR #5520, and PR #5522 all repair the `imeLatchRef` → `imeLatch` reference at useDialogFocusTrap.ts:85. Not dispatching a duplicate fix; one of these unblockers merging resolves main.

**Comment by bolichen97** [comment]
🤖 Kiro Crew Auto-Pipeline [operator: bolichen97#66809557]: Already fixed on `main`. Commit 2ce111e (PR #5522, "fix(ci): repair the three main-branch breakages failing every open PR", merged 2026-08-24T07:34:50Z) changes `website/src/hooks/useDialogFocusTrap.ts:85` from `imeLatchRef.current!.claimKey(e)` to `imeLatch.claimKey(e)`, resolving the #5482×#5473 semantic merge conflict. No `imeLatchRef` reference remains; `tsc` is green on current main HEAD. Closing as fixed; reopen if it recurs.
