### PR TITLE
fix(dev-fleet): sync prune-drain test double with _worktree_remove signature

### LINKED ISSUE #6743: test_devfleet_prune_shutdown_drain fails on main: stale fake_remove signature times out the drain on every branch
# Dev Fleet prune-shutdown-drain tests fail on origin/main (cross-merge breakage)

## Summary

`test/test_devfleet_prune_shutdown_drain.py` has 3 tests that fail deterministically on **pristine `origin/main`**, so the breakage is inherited by every PR branched from or rebased onto main. Confirmed reproducing locally at the current main tip and on PR CI across **both** `ubuntu-3.10` and `Windows` shard 2:

- `test_cleanup_drains_prune_worker_and_clears_handle`
- `test_worker_is_retained`
- `test_cleanup_stays_pending_and_holds_lock_until_mutation_releases`

All three fail with `asyncio.TimeoutError` after the 5s test timeout.

## Repro

```bash
git worktree add ../wt-check -b check origin/main
cd ../wt-check
.venv/bin/pytest test/test_devfleet_prune_shutdown_drain.py -q
# => 3 failed, 2 passed
```

## Failing output (root-cause line)

The `TimeoutError` is a *symptom*. The captured log shows the real failure — the prune worker crashes before it can complete the drain:

```
ERROR kiro_crew.apps.builtins.dev_fleet.server:server.py:5104 dev-fleet prune: item 'wt-x' failed
Traceback (most recent call last):
  File ".../dev_fleet/server.py", line 5089, in _prune_one
    res = await _worktree_remove(
                ^^^^^^^^^^^^^^^^^
TypeError: _start_prune.<locals>.fake_remove() got an unexpected keyword
           argument 'discard_untracked_paths'
```

## Root cause (precise mechanism)

This is a **cross-merge breakage between two independently-green PRs that touched the same worktree-removal path**, not a shutdown deadlock:

- **PR #6542** (`fix(dev-fleet): tell tracked dirt from untracked scratch when removing a worktree`, main commit `5c24d7727`, merged **2026-08-28 22:57 -0700**) added a `discard_untracked_paths` keyword to `_worktree_remove(...)` and made `_prune_one` pass it: `server.py:5089` now calls `await _worktree_remove(name, force=..., progress=..., _caller=..., discard_untracked_paths=_discard_paths.get(nm))`.
- **PR #6717** (`fix(dev-fleet): drain the prune worker on gateway shutdown`, main commit `afc8be653`, merged **2026-08-28 23:09 -0700**, 12 minutes later) **added** `test/test_devfleet_prune_shutdown_drain.py`. Its `fake_remove` test doubles monkeypatch `_worktree_remove` with the signature `async def fake_remove(nm, *, force, progress, _caller)` — no `discard_untracked_paths` parameter.

`#6542` is an ancestor of `#6717` on main, but `#6717`'s **CI green run was on a base predating `#6542`** (the two PRs raced; each was green against a base that lacked the other's change). Once both landed, the stub is missing the keyword `_prune_one` now passes.

Chain of consequence on main:
1. `_prune_run` starts the prune worker task and `_prune_one` calls the monkeypatched `_worktree_remove` **with** `discard_untracked_paths=...`.
2. The stub has no such parameter → `TypeError` → the prune worker task dies with an exception.
3. The shutdown-drain logic under test waits for the worker to reach a clean completion/handle-clear that never happens because the worker already crashed.
4. The test's `asyncio.wait_for(..., timeout=5.0)` expires → `TimeoutError`.

## Production bug or test debt?

**Test-contract only.** The production shutdown-drain code (`#6717`) and the `discard_untracked_paths` plumbing (`#6542`) are both correct; only the test double is stale — it does not mirror the current `_worktree_remove` signature. There is no real shutdown deadlock.

## Fix approach

Add `discard_untracked_paths=None` to both `fake_remove` stubs so they mirror the production `_worktree_remove` signature that `_prune_one` invokes. Smallest possible change; timeouts are left untouched (raising them would only mask the crash). After the fix the tests complete in ~0.5s instead of timing out at 5s.

Verification: the 3 tests pass; the full `test/test_devfleet_prune_shutdown_drain.py` (5 tests) and the combined `test/test_devfleet*.py` set (12 tests) all pass; flake8/isort/black clean on the touched file.

### PR DESCRIPTION
**Pull request by RohanK6**
## Problem / Motivation
`test/test_devfleet_prune_shutdown_drain.py` (added by #6717) fails on `main` itself: 3 of its 5 tests hit their 5s `asyncio` timeout on every platform, so **every open PR inherits a red Backend Tests shard 2** (and a failed Coverage Gate) via rebase. Fixes #6743.

## Why it matters
Main's own CI is red and all in-flight PRs are blocked on failures their diffs cannot cause. Until this lands, contributors either misdiagnose their PRs or burn re-rolls against an inherited failure.

## What changed (motivation → approach → change)
Reproduced at pristine `origin/main`: the prune worker crashes with `TypeError: fake_remove() got an unexpected keyword argument 'discard_untracked_paths'` — the tests' `fake_remove` doubles predate the `discard_untracked_paths` keyword that `_prune_one` now passes to `_worktree_remove` (a cross-merge: both contributing PRs were green on their own bases). The crash means the shutdown drain never observes completion, so the tests wait out their timeouts. Production code is correct; the doubles are stale. Change: both `fake_remove` stubs now accept `discard_untracked_paths=None` (keyword-only), mirroring the production signature they stand in for.

## Tests
- Before: `pytest test/test_devfleet_prune_shutdown_drain.py` → 3 failed (5.01s timeout each), 2 passed — at pristine `origin/main`.
- After: 5 passed in 0.5s; full `test/test_devfleet*.py` set → 12 passed.
- flake8 / isort / black clean on the touched file.

## Manual verification
Ran the failing trio under the repo venv at the exact main tip (`afc8be653`) to confirm red, then on this branch to confirm green; the captured worker log shows the `TypeError` disappearing with the stub fix.

## Screenshots / video
 Test-only change; no user-visible surface.

## Related Issues
Fixes #6743. Context: #6717 (introduced the tests), and the cross-merged change that added `discard_untracked_paths` to `_worktree_remove`.

## Checklist
- [x] Tests pass locally (5/5 in the file; 12/12 devfleet set)
- [x] Lint/format gates clean
- [x] One commit, conventional-commits subject
- [x] Issue linked (Fixes #6743)

## Contribution License Agreement
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by RohanK6** [comment]
Superseded by maintainer PR #6747 (`4f586e311`, "test(dev-fleet): match the prune-shutdown fakes to the current remove signature"), which landed the same fix — the stale `fake_remove` doubles now accept the `discard_untracked_paths` kwarg. Closing in its favor; thanks for the quick upstream turnaround.
