### PR TITLE
fix(windows): spawn one-shot kiro-cli reads at the configured sandbox tier

### PR DESCRIPTION
**Pull request by bolichen97**
## The bug

On Windows, opening Kiro Crew logged this every 8 seconds and the model picker offered **only `auto`**:

```
WARNING kiro_crew.dashboard.handlers.agents: api_models failed; returning 503 for client retry
  File "kiro_crew/dashboard/handlers/agents.py", line 888, in api_models
    argv, cleanup = wrap_argv(argv)
kiro_crew.sandbox.SandboxUnavailableError: Sandbox backend unavailable and
allow_unsandboxed_exec is not set. ... Probe detail: not Linux.
```

Both symptoms are one cause. `wrap_argv`'s `mode` parameter defaults to `"auto"`, which coincides with the shipped `agent.sandbox` default but **ignores what the operator configured**. Where `agent.sandbox` is an explicit `"off"` — isolation deferred to kiro-cli's own internal sandbox, which cannot nest inside Kiro Crew's — three one-shot `kiro-cli` reads took that parameter default (or a hardcoded `"standard"`) and so requested a **stricter** tier than the interactive ACP spawns, which thread the configured mode through their `sandbox_mode` constructor argument.

On a host with no backend at all — **any Windows host**, macOS >= 26 — `wrap_argv` fail-closes on that request while chat runs normally:

| Site | Symptom |
|---|---|
| `/api/models` (`--list-models`) | 503 on every 8s poll. The frontend's degraded fallback deliberately exposes only the `auto` sentinel (it must never offer canonical registry keys the ACP CLI rejects), so the picker showed **exactly one entry**. |
| `whoami` identity fetch | Failed permanently. Identity failure is non-fatal by design, so the credit pill's account email silently blanked. |
| `/usage` text scrape | The refusal fed the failure backoff that eventually parks it — despite being a **billed** turn that never ran. |

Two clarifications, both from review:

- This is **not** the macOS kiro-cli/Kiro Crew sandbox conflict. On Windows the probe reason is literally `not Linux`; there is no backend to conflict with.
- The affected population is **operators with an explicit `agent.sandbox="off"`**, not default installs. `ba54a66a` flipped the shipped default from `"off"` to `"auto"`, so on a *default* Windows install chat and these reads all fail closed together and the remedy is the `agent.sandbox_allow_unsandboxed_exec` opt-in, not this seam. (An earlier revision of this description said otherwise; that was wrong.)

## The fix

New `sandbox.configured_sandbox_mode()` (owning module: `sandbox.py`) returns `agent.sandbox`, falling back to `"auto"` **with a warning** when the config can't be read — an unreadable config must not be a way to obtain a *looser* tier. All three sites now pass it explicitly.

Because chat and these reads now resolve the **same key**, a one-shot read can never be stricter than the session it accompanies — nor looser. Governance still clamps the result up via `_clamp_sandbox_mode`, so a `sandbox.min_level` floor overrides it like any other caller-supplied mode.

`wrap_argv`'s own default is deliberately **unchanged**: callers that pin a tier independent of config (the prerequisite probes' `strict`, the credential-free registry clones) must keep it.

A **genuine** refusal — the tier resolving to `"auto"` on a backendless host — is now caught ahead of the generic `except` and answers 503 with a machine-readable `code: "model_list_sandbox_unavailable"` plus the sandbox layer's own remedy text, instead of an anonymous "model list unavailable" that no amount of retrying clears. It stays a 503 because the "degraded, keep the last-good list and poll" contract is what stops the picker caching an empty result.

### Also fixed: these wraps were blocking the event loop

`/api/models` was already calling `wrap_argv` **inline on the loop** before this change, and resolving the mode adds a second blocking read. Both now run in `subprocess_executor()`:

- `configured_sandbox_mode()` stats — and on a cache miss re-reads + revalidates — `config.json`
- `wrap_argv` → `detect_backend` can cold-probe the backend with a synchronous `subprocess.run(..., timeout=5)`

The mode is resolved *inside* each helper: passing `mode=configured_sandbox_mode()` into `run_in_executor`/`functools.partial` evaluates it eagerly on the loop and offloads only half the work. Since this endpoint is polled every 8s while degraded and the usage refresh runs on a timer, an inline wrap stalls chat, cron and the liveness heartbeat on exactly the host where the probe is slowest.

The helpers are deliberately *named* for the chokepoint they call — `test_spawn_audit.py` recognises a routed spawn by finding a `wrap_argv` token in the spawning function's own source, so moving the wrap into a differently-named helper makes a still-sandboxed spawn read as unrouted. That gate caught it and is green again.

## Accepted trade, stated explicitly

The two `sessions.py` sites previously pinned `"standard"`, so with an explicitly configured `agent.sandbox="off"` they now spawn with no Kiro Crew wrap where they used to hide `_STANDARD_DIRS` (`.gnupg`, `.config/gcloud`, `.azure`, `.docker`, auth-staging).

This is reachable **only** on a host where the operator already declared `"off"` and thereby accepted that posture for **every chat turn** — a far larger and longer-lived exposure than one `whoami`. It is the same posture the interactive chat spawn of that identical binary already runs under on that identical host; the asymmetry was an accident of a hardcoded literal, not a designed boundary. Both spawns are fixed argv with no agent-influenced arguments, the `/usage` scrape is itself opt-in (`dashboard.usage_text_scrape_enabled` defaults to `False`), and an explicit `"off"` now emits a one-time `SECURITY` warning. An operator wanting the wrap back sets `agent.sandbox="auto"` — the shipped default — which then applies uniformly to chat *and* these reads.

## Verification

Reproduced and confirmed fixed on the real Windows host:

```
before:  wrap_argv(['kiro-cli','chat','--list-models'])         -> RAISED no_backend / "not Linux"
after:   configured_sandbox_mode() == 'off'  -> wrap OK
GET /api/models: STATUS 200 | models: 26     (was 503 | 1 auto-only row)
```

Tests pinning the fix (`test_api_models_retry.py`): the tier is passed explicitly and matches config; the helper equals the chat path's tier; an unreadable config fails secure *and* warns; a real refusal carries the `code` and logs the remedy. The tier test was verified to **fail** against the pre-fix call site, so it is not vacuous.

Gates: `flake8`, `isort`, `docs-lint`, `scrub-lint`, `check_brand_name` all clean. `mypy src/kiro_crew` — normalized error set byte-identical to base (the 155 local errors are the Windows-only `fcntl`/`os.getuid` artifact; CI runs mypy on Linux). Full suite: 218 failures, failure set **byte-identical to a pristine `HEAD` worktree** — all pre-existing local-environment artifacts (142 × `WinError 1314`, non-admin shell vs. admin CI runner; the rest POSIX-path assertions). Existing `wrap_argv` test stubs were widened to `(argv, **kwargs)` so an added keyword can't masquerade as a degraded response.

## Docs

`modules/acp-client.md` (the rule, affected sites, symptoms, off-loop requirement, accepted trade), `modules/security.md` (callers must pass the configured tier), `guides/windows-install.md` (how the picker and credit pill follow chat's posture, per-case).

### CODE REVIEW

**Comment by bolichen97** [comment]
## Disposition of the GPT 5.6 Review findings on `0e5bb37d`

### `docs/guides/windows-install.md:130` — **fixed** (`cb7ceb49`)

GPT is right and I was wrong. I wrote this against a base that predated `ba54a66a` ("fix(security): change sandbox default from 'off' to 'auto'"), which landed in the 86 commits I rebased across. Verified on a clean data home:

```
FRESH INSTALL agent.sandbox = 'auto'      # not 'off'
chat at auto on Windows     -> RAISED no_backend | not Linux
```

So on a **default** Windows install chat fail-closes too, and my "chat works but the picker doesn't" framing only holds for a config with an explicit `"off"`. Corrected in the Windows guide (which now states both cases and names the opt-in as the default-install remedy), `modules/security.md`, `modules/acp-client.md`, the two code comments, and the test docstring. No behavior change — the mechanism was right, the stated precondition was not.

### `sessions.py:504` BLOCKING — **rebutted**, with evidence

> `agent.sandbox="off"` + enabled usage scrape -> `_fetch_usage_bg` -> `wrap_argv(mode="off")` -> `kiro-cli chat` runs with credential directories visible.

The premise reproduces; the conclusion doesn't follow. **In that exact scenario the long-lived chat session already runs at `"off"`** — `session.py` and `slack/gateway.py` pass `agent.sandbox` verbatim:

```
agent.sandbox     = 'off'   (explicitly configured)
usage_text_scrape = True
scrape tier = 'off'         <- this PR
chat  tier = 'off'          <- already, unchanged by this PR
```

The finding describes an exposure the operator **already accepted for every chat turn** by declaring `"off"`. This PR does not create it and does not widen it: it removes an asymmetry where a one-shot `whoami` demanded stricter confinement than the unbounded interactive session beside it. A single fixed-argv `/usage` read is a strictly smaller exposure than the session it accompanies.

The proposed fix — keep `mode="standard"` — also **does not deliver isolation on the host in question**, and reinstates the bug:

```
wrap_argv([...], mode="standard")  on Windows
  -> RAISED no_backend ( not Linux )
```

There is no backend on Windows, so `"standard"` yields a *refusal*, not a confined spawn. Pinning it back means the credit pill silently loses its account email and the billed `/usage` scrape keeps burning its failure backoff on a spawn that never runs — the reported bug, unfixed — while gaining zero isolation.

Also relevant: the scrape is opt-in (`dashboard.usage_text_scrape_enabled` defaults to `False`), both spawns are fixed argv with no agent-influenced arguments, an explicit `"off"` now emits a one-time `SECURITY` warning (added by `ba54a66a`), and `_clamp_sandbox_mode` still lets an enterprise `sandbox.min_level` floor override the value. An operator wanting the wrap sets `agent.sandbox="auto"` — the shipped default — which then applies uniformly to chat *and* these reads.

Happy to be overruled by a maintainer if the asymmetry is considered load-bearing, but I don't think a read can justifiably be held to a stricter standard than the session it reports on.

**Comment by bolichen97** [comment]
## Design Review suggestion — **fixed** (`e4873e4c`)

> The new `sandbox.py` docstring and PR narrative claim the shipped `agent.sandbox` default is `"off"`, but the branch already flips it to `"auto"` (`ba54a66a`, and `loader.py:4591` at HEAD)

Correct, and thank you — this was the one site I missed when correcting the same error elsewhere in the previous push. `configured_sandbox_mode()`'s docstring now states that `"auto"` *coincides with* the shipped default but ignores what the operator configured, and scopes the affected population to explicit-`"off"` operators rather than default installs. It also now records the invariant that motivated the seam: passing the configured value keeps a one-shot read from being stricter than the session it accompanies, and cannot make it looser, because both resolve the same key.

Verified no stale claim survives anywhere in `src/`, `docs/`, or `test/`. Merged docs and code comments now agree with `loader.py` on who is affected.

The PR description above still describes the pre-correction framing in places; the authoritative statement is the code + `modules/acp-client.md` / `modules/security.md` / `guides/windows-install.md` as of this SHA.

**Comment by bolichen97** [comment]
## `agents.py:870` / `sessions.py:498` BLOCKING — **fixed** (`eb320ff4`)

GPT is right, and this one I should have caught myself: **both ACP spawn paths already pass this flag** (`client.py:2326` `is_kiro_cli=not self._is_claude`, `runtime.py:679` `is_kiro_cli=True`) precisely because basename detection is unreliable. My three new call sites left it at `None`.

Verified the misclassification:

```
/usr/bin/kiro-cli                                    -> True
C:\Users\x\Toolbox\bin\kiro-cli.exe                  -> False   <-- Windows
/Applications/Kiro CLI.app/Contents/MacOS/kiro-cli   -> True
/Users/x/.toolbox/bin/kiro-cli-wrapper               -> False   <-- shim
```

And verified the consequence on the `mode="off"` path (macOS, kiro internal sandbox on), instrumenting `_sandbox_env_unset_args` to see whether the delegation branch is entered at all:

```
is_kiro_cli=None -> delegation branch entered? False | argv[0]= ...kiro-cli.exe
is_kiro_cli=True -> delegation branch entered? True  | argv[0]= env
```

So with `None` the spawn skips the delegation branch **and its credential-env scrub** and returns raw argv — exactly as described. With `True` it enters the branch and the `env -u …` prefix is applied. Fixed at both sites (three call paths: `--list-models`, `whoami`, `/usage`), with the reasoning recorded in each docstring and in `modules/acp-client.md` so the next one-shot `kiro-cli` spawn doesn't repeat it.

Worth noting for anyone reading the diff: a first check of this used `mode="standard"` and appeared to show no scrub either way. That was a bad probe, not a second bug — `_sandbox_env_unset_args("standard", …)` is legitimately empty, since `standard` deliberately preserves AWS/SSH for git-over-SSH and the AWS CLI. The instrumented check above is the one that actually distinguishes the branches.

### Local gate

`flake8` / `isort` / `docs-lint` / `check_brand_name` clean; `test_api_models_retry.py`, `test_api_models_entitlement.py`, `test_spawn_audit.py` pass. `test_sandbox_cc_mode.py` has 15 failures locally, but the failure set is byte-identical with and without this change (`AttributeError: module 'os' has no attribute 'getuid'` — the Windows-local artifact; those launcher tests are Linux-only and run fine in CI).
