### PR TITLE
feat(ledger): record the creating session on session/opened

### PR DESCRIPTION
**Pull request by chenmingwei23**
## Problem / Motivation

The append-only session ledger (the "crew log") records what a session did, but not who made it. A worker session that a conductor opened through `session_create` writes a `session/opened` entry identical to a tab a person opened by hand. Nothing in any ledger says "this session exists because that session asked for it", so no tree of sessions can be folded from the log. The only record of that edge today is `_created_by` on the in-memory slot and the transcript's metadata line, neither of which is the ledger.

## Why it matters

Session control now lets one session create and drive others, and crew mode will lean on that. A conductor's fan-out is invisible in the record that is supposed to be the source of truth: a reader cannot answer "which sessions did this one spawn" from the ledgers, the System page cannot be made a projection of the log, and a session tree would have to be assembled from a second, in-memory source that is gone after a restart.

## What changed (motivation → approach → change)

A reader can now tell from the ledgers alone which session opened which. A created session names its creator in its own `session/opened` entry.

| | Before | After |
|---|---|---|
| `session/opened.data` on a `session_create` child | `agent, slot, model, cwd, owner, resumed` | same, plus `parent {slot, sid?}` |
| a person's own tab, a fork | no lineage | no `parent` key at all |
| registry (`crew_log/entry_types.py`) | `parent` undeclared, so a caller could not write it | `parent.slot` required, `parent.sid` optional, other members refused |

The edge is written on the **child**, because the child is the one side that holds both halves. `session_create` (`dashboard/session_control.py`) stamps three facts on the new slot at mint, before any turn: the creator's key (`_created_by`), the creator's ACP session id read off the live caller handle (`_created_by_sid`), and an in-memory witness that this gateway process did the stamping (`_lineage_minted`). At the child's first turn the chat runner (`dashboard/chat_runner.py`, `_ledger_lineage`) passes the two ids to the emitter's `on_session_opened` (`crew_log/emit.py`) as `parent_slot` / `parent_sid` only when the witness is set; nothing is looked up live. The sid and the witness are never written to the transcript: that file is editable by an agent's file tools, and the crew log is fenced from those tools precisely so nothing in it can be forged as gateway-authored, so `created_by` read back from transcript metadata after a restart still serves the ownership boundary but is never promoted to lineage (`dashboard/chat_persistence.py`). A child whose gateway restarted between mint and its first turn writes no `parent`. The creator can never write this edge itself: the child's ACP session id -- the log's unit id -- does not exist yet when `session_create` runs, which is the same blocker the emitter spec already records for `subagent/*`.

The sid is frozen at mint rather than read at the child's first turn because a creator slot can be closed and replaced in between; a live read would cite the replacement's ledger in an entry that is never rewritten. The id is backend-authored, so it is bounded where it is retained: `MAX_ACP_SESSION_ID_LEN` (`kiro_crew/validation.py`, a leaf both the ACP layer and application code may import without crossing the agent-SDK boundary) is the one constant for every store of a backend session id -- the native-child rosters in `acp/runtime.py` and `acp/session_handle.py` now name it instead of literals -- and an id past it is dropped at mint, never truncated; the sid is optional, so absent is a legal record.

```mermaid
flowchart LR
  subgraph before [Before]
    P0["creator ledger"]:::ctx
    C0["child ledger<br/>session/opened"]:::ctx
  end
  subgraph after [After]
    P1["creator ledger<br/>(sid)"]:::ctx
    C1["child ledger<br/>session/opened<br/>parent {slot, sid}"]:::added
    C1 - "slot, sid" --> P1
  end
  classDef added fill:#DCFCE7,stroke:#16A34A
  classDef changed fill:#FEF3C7,stroke:#D97706
  classDef removed fill:#FEE2E2,stroke:#DC2626,stroke-dasharray:4 3
  classDef ctx fill:#E0F2FE,stroke:#0284C7
  linkStyle 0 stroke:#16A34A,stroke-width:2px
```
Legend: green = added after this PR, blue = unchanged, shown for context.

The child's entry now points at the session that made it, with the id the creator had at mint; the creator's file is untouched.

`sid` is a citation, not the tree key. A slot outlives its ACP session, so the creator's id names the unit that was live when the child was made; a fold that builds the tree keys it by `slot`. `sid` is omitted rather than written empty when the creator had no live handle at mint, and the whole `parent` object is omitted when nobody created the session, so a reader can tell "no creator" from "creator unknown". The three specs (`crew-log-core.md`, `crew-log-emitter.md`, `session-control.md`) state the field, the side it is written from, and why.

No projection or UI is built here: the System page tree is the next PR, folded from this field.

## Tests

- `test/test_crew_log_types.py`: the canonical `session/opened` example carries `parent`, so the registry suite checks its nested shape; two refusal cases lock in `parent` without `slot` (`data.parent.slot`) and an undeclared member (`data.parent.creator`).
- `test/test_crew_log_emit.py`: five tests -- a created session records `{slot, sid}`; a creator with no sid is recorded by `slot` alone; a session nobody created has no `parent` key; a `sid` with no `slot` names no creator; a re-attach (`resumed=True`) writes the creator again.
- `test/test_session_control.py`: `create_session` freezes the caller's ACP session id on the child and sets the mint witness, and the birth metadata carries `created_by` but never the sid; the frozen value does not follow a replaced creator handle (the mutation guard for the live-read defect); an id past `MAX_ACP_SESSION_ID_LEN` is dropped at mint; a slot nobody minted in this process has no witness; and `_ledger_lineage` yields the creator only for a witnessed mint -- restored or hand-set attribution yields nothing, a witnessed mint without a handle yields the slot alone.
- `test/test_member_session_control.py`: the recent-session restore path restores `created_by` but ignores a `created_by_sid` found in the metadata line and leaves the witness unset; a save -> rehydrate round trip through the real serializer writes `created_by` and never the sid or the witness.

## Manual verification

N/A - unit coverage sufficient. The runtime change is one call site passing two slot attributes through; `state.get_slot` returns `None` for an absent creator and `session_id_of` returns `""` for a missing handle, both of which the emitter tests cover as the no-sid and no-parent branches.

## Related Issues

Part of #11484, which tracks the reader of this field: the session-tree projection and the System page Sessions tab. This PR closes nothing on merge.

## Checklist

- [x] At most two commits (one is the norm), with a Conventional Commits title (`feat|fix|docs|refactor|perf|test|chore|ci|build|revert: ...`)
- [x] Existing tests pass and new tests added for new functionality
- [x] Self-review completed; code follows project style guidelines
- [x] Documentation updated (if applicable)
- [x] No secrets, credentials, or internal references in the diff

### CODE REVIEW

**Comment by chenmingwei23** [comment]
**Intent:** Make the append-only session ledger carry the one lineage fact it can carry today: a session that another session created through session_create names its creator on its own session/opened entry (parent {slot, sid?}), so a tree of sessions can later be folded from the log instead of from in-memory state.
**Not a goal:** No tree projection, no System page change, no lineage for spawn_run subagents or forks, no crew-ledger writer. Each of those is a follow-up on top of this field.

**Comment by chenmingwei23** [comment]
CI note (not a finding on this diff): the two red backend shards, Backend Tests (3.12, 2) and Backend Tests (Windows) (3), fail on the same two tests, test/test_fargate_launch_engine.py::test_engine_satisfies_the_launch_engine_protocol and ::test_signin_handle_has_every_signin_handle_protocol_member (FargateLaunchEngine.begin_signin lacks the login_target keyword the LaunchEngine protocol grew). Both fail identically on main at the merge-base; this PR touches neither file. Coverage Gate fails closed on the shard failure. Fixes are open as #11422 / #11426 / #11432 / #11442; this branch will be rebased once one lands, which re-runs CI.

**Comment by chenmingwei23** [comment]
- **Item 1 - zero consumers (span=ac6961f64e8c)**: accepted-and-deferred
> The reader is the session-tree projection tracked in #11484 (label deferred-finding, assignee chenmingwei23, Due 2026-10-01): fold header + session/opened of each session ledger, keyed by slot, served on /api/sessions/memory for the System page.
> Capture precedes the reader on purpose: an append-only log cannot backfill a lineage fact that was not recorded, so the field ships first and the projection is the next PR against it.
> The shape being locked in (slot as tree key, sid as citation of the creator ledger) is the one the projection in #11484 consumes; the issue names it so the two cannot drift.

**Comment by chenmingwei23** [comment]
self-added: yes
mechanism: creator ACP session id frozen on the child slot at mint (_created_by_sid), persisted in birth metadata beside created_by
- **A replacement session is recorded as the creator (span=db37e66c9e96)**: fixed in 0d0bcdc424f8842576917885cef75dfb71c3c57f
> The creator sid is no longer read live at the child first turn. session_create stamps slot._created_by_sid from the live caller handle at mint (session_control.py), the value rides the birth metadata and is persisted/rehydrated beside created_by (session_control.py, chat_persistence.py), and chat_runner.py passes that frozen value as parent_sid.
> Regression: test_session_control.py::test_the_creator_session_id_is_frozen_at_mint_not_read_live replaces the creator handle after mint and asserts the child still carries the mint-time id, on the slot and in its birth metadata; test_member_session_control.py covers the restore path.

**Comment by chenmingwei23** [comment]
self-added: yes
mechanism: MAX_ACP_SESSION_ID_LEN in acp/types.py, one named bound for every retained backend session id, applied at mint and on restore
- **Bound the retained creator session ID (span=36bec42fc986)**: fixed in 354b40228e185366d43a470037b8fad14cd7d872
> The creator sid is now bounded where it is retained: session_control drops an id past MAX_ACP_SESSION_ID_LEN at mint (stored as absent, never truncated, so it cannot reach the birth metadata or oversize the session/opened entry), and both chat_persistence restore paths apply the same constant on the way back in.
> One named constant for the population: acp/runtime.py native-child roster gate now uses MAX_ACP_SESSION_ID_LEN instead of its literal 128, so no two stores bound backend session ids differently.
> Regression: test_session_control.py::test_an_oversize_creator_session_id_is_dropped_at_mint_not_retained and test_member_session_control.py::test_an_oversize_persisted_creator_sid_restores_as_absent.

**Comment by chenmingwei23** [comment]
- **Item 1 - zero consumers (span=424cdb602179)**: accepted-and-deferred
> The reader is tracked in #11484 (label deferred-finding, assignee chenmingwei23, Due 2026-10-01) and the PR body now links it under Related Issues: fold header + session/opened of each session ledger, keyed by slot, served on /api/sessions/memory for the System page.
> Capture precedes the reader on purpose: an append-only log cannot backfill a lineage fact that was not recorded, so the field ships first and the projection is the next PR against it.
> The shape being locked in (slot as tree key, sid as bounded citation of the creator ledger) is the one #11484 consumes, so the two cannot drift.

**Comment by chenmingwei23** [comment]
self-added: yes
- **function-local imports in session_control.py violate top-level-imports (span=603a4f56682a)**: fixed in c50726e17220a1eeac6b3864e549821da6d5fadd
> Both imports are now module-scope: `from kiro_crew import session_ledger_emit` and `MAX_ACP_SESSION_ID_LEN` from `kiro_crew.validation`. Neither module imports the dashboard package, so no cycle justified the local form.
> The constant moved from acp/types.py to kiro_crew/validation.py in the same change: the agent-SDK boundary gate forbids application code importing kiro_crew.acp, and validation.py is a leaf both the ACP runtime and the dashboard already import (MODEL_ID_RE, MAX_LONG_STRING).

**Comment by chenmingwei23** [comment]
self-added: yes
- **in-method imports with no circular-import comment (span=29914e6a98b5)**: fixed in c50726e17220a1eeac6b3864e549821da6d5fadd
> Moved to module scope in session_control.py: `from kiro_crew import session_ledger_emit` and `from kiro_crew.validation import MAX_ACP_SESSION_ID_LEN, MAX_LONG_STRING`. No cycle existed, so no comment was warranted; the local form was simply wrong.
> The bound constant now lives in kiro_crew/validation.py (not acp/types.py) so the module-scope import does not cross the agent-SDK boundary the CI gate enforces.

**Comment by chenmingwei23** [comment]
- **Item 1 - zero consumers (span=f51204cdb2a7)**: accepted-and-deferred
> Same reader as the two earlier rounds, re-raised on this head: the session-tree projection tracked in #11484 (label deferred-finding, assignee chenmingwei23, Due: 2026-10-01) folds header + session/opened of each session ledger, keyed by parent.slot, and serves parent on /api/sessions/memory for the System page Sessions tab. The PR body links #11484 under Related Issues.
> Capture precedes the reader on purpose: an append-only log cannot backfill a lineage fact that was not recorded, so the field ships first and the projection is the next PR against it.

**Comment by chenmingwei23** [comment]
- **Item 2 - zero consumers of the sid half (span=35b8ee63139a)**: accepted-and-deferred
> The sid consumer is now named in #11484 (label deferred-finding, assignee chenmingwei23, Due: 2026-10-01): the projection resolves parent.sid to the creator ledger path (ledger_path("session", sid)) so a System page row links to the exact creator log. The slot alone cannot do that once a slot key is reused; the sid is the citation of the creator ledger as it was at the moment of creation.
> The sid half is not deferred with it because it cannot be: the creator handle may be replaced after the child is minted (GPT span db37e66c9e96, fixed in this PR), so the frozen id is captured at mint or lost forever. The slot field, the two save sites, the two bounded restore sites and the mint-time bound are the cost of writing that one value correctly, and they are covered by test_the_creator_session_id_is_frozen_at_mint_not_read_live, test_an_oversize_creator_session_id_is_dropped_at_mint_not_retained and test_an_oversize_persisted_creator_sid_restores_as_absent.

**Comment by chenmingwei23** [comment]
self-added: yes
mechanism: created_by_sid bounded at mint and re-clamped on both restore paths
- **Oversized restored creator IDs remain persisted (span=1ce50744f47d)**: rebutted
> The finding needs an over-limit created_by_sid already on disk. The only writer clamps at mint (session_control.py:1231, an id longer than MAX_ACP_SESSION_ID_LEN is dropped, never stored) and both save sites (chat_persistence.py:3124, :3469) write the field only when the slot holds a value, so KiroCrew never emits one; the value can only get there by editing the JSONL by hand. Both restore sites clamp on read (chat_persistence.py:1131, :1679), so such a string is read back as "" and never reaches memory, the child ledger, or any API row. Nothing is corrupted or lost: the inert string sits in a file its editor already controls.
> The proposed remedy (clearable-field semantics on the partial-save mirror plus a rows-only branch) is permanent save-path complexity to scrub an inert value; the Opus adjudication on this head reached the same conclusion (disproportionate-remedy). The two bounds are pinned by test_an_oversize_creator_session_id_is_dropped_at_mint_not_retained (mint side) and test_an_oversize_persisted_creator_sid_restores_as_absent (restore side).

**Comment by chenmingwei23** [comment]
**CI note (head 3d6bbe05d8): the two red Windows shards are inherited from main, not from this PR.**

`Backend Tests (Windows) (5)` and `(7)` fail on six tests this PR does not touch:

- `test/test_session_control.py::test_private_creator_cannot_change_memory[writer-canonical]` / `[public-worker-canonical]` -- `assert 'agent_store_mismatch' == 'memory_delegation_denied'`
- `test/test_session_control.py::test_create_refuses_unreadable_delegation_identity[ValueError]` / `[OSError]` -- `assert 400 == 403` / `OSError` escapes
- `test/test_member_session_control.py::TestMemberChildPrivateBinding::test_global_caller_cannot_grant_a_child_private_authority` and `::test_a_v1_child_writes_no_private_binding` -- `assert 'member-radar' is None`

The same six fail on a clean detached checkout of `origin/main` (419d9d7b90) with nothing from this branch applied. They look like the subject of #11593 (`fix(session-control): authorize a created child on the store it is bound to`); this branch will be rebased once that lands. Every other check on this head is green so far.

**Comment by chenmingwei23** [comment]
- **Item 5 - point patch, 1 unfixed sibling (span=d69cb27a2c11)**: fixed
> `_note_native_child` in `src/kiro_crew/acp/session_handle.py` now bounds a child id with `MAX_ACP_SESSION_ID_LEN` instead of the literal 128, so the constant's comment ("one constant for the whole population") is true of every store of a backend session id in the tree: both native-child rosters (`acp/runtime.py`, `acp/session_handle.py`), the frozen creator id at mint, its birth metadata and both restore paths. Same value, no behavior change; the agent-SDK boundary gate passes because `kiro_crew.validation` is a leaf both sides already import. Fix is in head d9422fa93d; the PR body names the second roster.
> The one remaining 128 near a session identifier (`artifacts.py` activity `session_id[:128]`) bounds the dashboard session KEY, an application-authored string outside this constant's population, so it is not a sibling.

**Comment by chenmingwei23** [comment]
**Retrospective (rounds 0-4), measured against the intent comment.** Run in-session: the review-delegate spawn path is unavailable in this session, so this is the writer's own assessment, stated as such.

Intent: a `session_create` child names its creator on its own `session/opened` as `parent {slot, sid?}`. Not a goal: tree projection, System page, subagent/fork lineage, crew-ledger writer.

| mechanism (round, introducing finding) | later findings inside it | removal: intent / defect | verdict |
|---|---|---|---|
| creator sid frozen at mint on the slot + birth metadata + persistence (r0, GPT db37e66c9e96) | r1 bound, r3 restore clamp, r4 sibling | intent keeps `sid?` on purpose (it is the join to the creator ledger, consumer named in #11484); a live read reopens the wrong-lineage defect | **keep** -- invariant: lineage never reads a live handle (`test_the_creator_session_id_is_frozen_at_mint_not_read_live`) |
| `MAX_ACP_SESSION_ID_LEN` in `validation.py` (r1, GPT 424cdb602179) | r4 FP d69cb27a2c11 (roster literal) | removal reopens unbounded retention of a backend string; a borrowed constant could not also replace the two roster literals | **keep** -- invariant: every retained backend session id names this one constant (four sites after r4) |
| re-clamp on both restore paths (r3, GPT 1ce50744f47d) | none | removal lets an over-long persisted line re-enter the slot | **keep** -- two lines, same constant |
| module-scope imports (r2, GPT/Opus advisory) | none | style only | keep |

> No subtraction: every mechanism traces to the `sid?` half the intent names, and the three follow-ons are the bound that half requires, not scope growth. Size +490/-20 is the intent plus its bound. Watch item: if #11484 later drops the sid consumer, the sid half and all three follow-ons go together.

**Comment by chenmingwei23** [comment]
- **Item 1 - zero consumers of `parent` (span=fd4a24a07494)**: accepted-and-deferred
> Same clearing condition as the earlier spans ac6961f64e8c and 35b8ee63139a (rounds 0 and 3): the consumer is #11484 (label deferred-finding, assignee chenmingwei23, Due 2026-10-01), whose body names the reads this item asks for -- a tree fold over one `session/opened` per session ledger keyed by `parent.slot`, resolving `parent.sid` to the creator ledger path for the System page row. The PR body's Related Issues carries `Part of #11484`.
> Writer-first is the only order available: the child's session id does not exist when `session_create` runs, and the field must be declared and written before any fold can read it. Shipping the reader in the same PR would put frontend work into a change scoped to the ledger record (see the intent comment's not-a-goal list). The retrospective after round 4 (issuecomment-5721674342) carries this as its one Watch item: if #11484 drops the sid consumer, the sid half and its bounds go together.

**Review by bolichen97 — DISMISSED** [review]

**Comment by chenmingwei23** [comment]
Rebased onto main to clear the conflict the crew-log rename (#11549) created under this branch. One
commit, still 16 files, 490 insertions and 20 deletions -- unchanged from the pre-rebase commit.
No behaviour change: the only added lines that differ from the original are prose.

The rename paired all but one file automatically. Resolved by hand:

- `dashboard/chat_runner.py` -- main renamed the emitter call while this branch added the
  `_created_by` / `_created_by_sid` comment and the two locals above it. Kept both: the new lines
  with main's `crew_log_emit` alias.

Three references survived the rebase OUTSIDE the conflict region, which is the part a rebase does
not tell you about:

- `dashboard/session_control.py` -- the new `from kiro_crew import session_ledger_emit` import and
  its `session_id_of` call site. Now `from kiro_crew.crew_log import emit as crew_log_emit`, matching
  the 10 other import sites on main. isort then moved the line, since `crew_log` sorts after `config`.
- `docs/system-specs/modules/session-control.md` -- a cross-reference to `session-ledger-emitter.md`,
  which is now `crew-log-emitter.md`. A dangling doc link, which no grep for module names catches.

Applied the naming rule to the prose this branch adds: 16 comment, docstring and spec lines that
described the renamed mechanism as "ledger" now say "crew log". The local variable `ledger` in
`crew_log/emit.py` is left alone -- that is main's own convention at six sites in that file, and the
`Ledger` class is deliberately not renamed yet.

Gates on the touched files: flake8, isort, black and mypy clean; docs lint passes; the black baseline
gate passes. Tests: `test_crew_log_emit.py`, `test_crew_log_types.py`, `test_member_session_control.py`
and `test_session_control.py` give **581 passed**, and `test_docs_crew_log_reference.py` 194 passed
(that one guards the `note=` wording I edited in the entry-type registry).

Two things left for you, since they are yours to decide:

- The body's prose still calls the mechanism "ledger" in several places, including the mermaid node
  labels. I updated only the five stale file paths and left your wording alone.
- `KIROCREW_SESSION_LEDGER` is now `KIROCREW_CREW_LOG`. Nothing in this branch names the flag, so
  there was nothing to change, but it is the spelling to use if you add one.

The full mapping other branches can apply mechanically is the same one I used here: paths,
identifiers, the fence-leaf sets that are deliberately not a straight substitution, and the list of
comments that must keep saying "ledger" because they name other mechanisms.

**Comment by chenmingwei23** [comment]
- **Item 1 - zero consumers of `parent` (span=a0da6cceff95)**: accepted-and-deferred
> Same item and same clearing condition as spans ac6961f64e8c, 35b8ee63139a and fd4a24a07494 on earlier heads: the consumer is #11484 (label deferred-finding, assignee chenmingwei23, Due 2026-10-01) -- a tree fold over one `session/opened` per session crew log keyed by `parent.slot`, resolving `parent.sid` to the creator's log for the System page row; the body's Related Issues carries `Part of #11484`.
> This head is the same change rebased onto main after the crew-log rename (#11549); nothing about the consumer question moved. Writer-first remains the only order available because the child's session id does not exist when `session_create` runs, and the retrospective after round 4 (issuecomment-5721674342) carries this as its Watch item.

**Comment by chenmingwei23** [comment]
Classifying the three test reds on `e7784f3adb`. Neither is this branch's.

**`Backend Tests (3.12, 2)` and `Backend Tests (Windows) (2)` -- #11634, main-side.**
`test/test_backend_cards.py::test_every_capability_set_is_classified_by_the_card`, failing with
`assert not ['ACP_BACKENDS_SELF_SERVED_ACP']`. It reproduces on a pristine `origin/main` at
`0d6675c4ec` with nothing applied, on Linux as well as Windows.

Two green changes collided: #11431 (`227b72b233`) added the classification test, #11428
(`abb8ee47d7`) then added a capability set and classified it nowhere. A two-point check pins the
first bad merge at `abb8ee47d7` -- the test passes at `227b72b233` and fails at `abb8ee47d7`.
Neither PR's CI could see it, because each run tested its branch against the main of that moment.

**`Backend Tests (Windows) (8)` -- already tracked, different defect.**
`test/test_workflows_service.py::test_finished_run_busy_slot_queues_turn`, `assert False`. This is
#10964 ("test_workflows_service.py fails on Windows shards across unrelated PRs"), with #11144
carrying the mechanism: the `on_done` assertion races a thread-pool flush behind a fixed
`asyncio.sleep`. It passes on Linux at current main and passed here on the four touched files, so
it is a Windows-shard timing flake rather than a new family.

**`GPT 5.6 Review`** is red and I am not classifying it yet. The job records one blocking finding,
security-class and withheld from adjudication, and points at a PR comment that has not been posted.
I will not guess at a finding I cannot read; once the comment lands, it gets either a fix or a
disposition on its merits.

Nothing here changes the rebase result: 16 files, 490 insertions, 20 deletions, one commit, no
behaviour change.

**Comment by chenmingwei23** [comment]
Two more shards went red after the comment above, and both are also main-side.

**`Backend Tests (Windows) (1)` -- #11635, main-side.** All 10 tests in
`test/test_acp_launch_goldens.py`, each with
`TypeError: _stub_common.<locals>.<lambda>() got an unexpected keyword argument 'forward_ssh_auth_sock'`.
It reproduces on pristine `origin/main` at `0d6675c4ec` as `10 failed, 19 passed`. First bad merge is
`727503fdfb` (#9131): `acp/client.py` began passing the keyword, and the capture harness's stub lambda
in `test/acp_launch_capture.py` was never given it. Passes at that commit's parent.

**`Backend Tests (3.12, 5)` -- flake, no issue.**
`test_pid_lifecycle.py::TestSyncKillProviderTree::test_reaped_leader_does_not_suppress_the_group_signal`,
one test, `assert <Signals.SIGKILL: 9> in [<Signals.SIGTERM: 15>]`. The whole
`TestSyncKillProviderTree` class passes on pristine main here, and this family was fixed on main by
#11491, so a single occurrence is a flake rather than a return of it. Worth a re-run, not an issue.

That accounts for all five test reds: #11634 on two shards, #11635 on one, #10964 on one, and one
flake. None of them is this branch's, and none is reproducible only with this branch applied.

**Comment by chenmingwei23** [comment]
- **Agent-writable metadata can forge gateway lineage (span=db37e66c9e96)**: fixed
> Real, and the fence's own rationale says why (`security/paths.py`: the crew log is fenced from agent file tools so nothing in it can be forged as gateway-authored; the transcript beside it is not fenced). Fix in e6585e001c: lineage is written only from a mint THIS gateway process witnessed. `session_create` sets an in-memory `_lineage_minted` beside the frozen sid (`state.py`, `session_control.py`); the sid is no longer written to birth metadata or the transcript and no longer restored on either path (`chat_persistence.py`, four sites removed, `MAX_ACP_SESSION_ID_LEN` import dropped there); `chat_runner.py` reads the pair through a new pure seam `_ledger_lineage(slot)` that yields nothing without the witness, so `created_by` restored from metadata still serves the ownership boundary but is never promoted to `session/opened.parent`. Cost, stated in the specs and body: a child whose gateway restarted between mint and its first turn writes no `parent`.
> Tests: `_ledger_lineage` pinned for a witnessed mint, a restored/hand-set slot (yields nothing) and a witnessed mint without a handle; the mint test asserts the metadata carries `created_by` but never the sid; both restore paths assert a persisted `created_by_sid` is ignored and the witness stays unset; the restore-clamp test is removed with the restore path it tested. 582 pass locally; black/flake8/mypy/docs-lint/boundary gate clean.
> Retrospective update (rounds 0-4 verdicts, issuecomment-5721674342): the round-3 mechanism "re-clamp on both restore paths" is now SUBTRACTED -- the restore path is gone -- and the round-0 persistence half of "sid frozen at mint" with it; the bound remains at mint only. Made directly because the review delegate path is unavailable in this session.

**Comment by chenmingwei23** [comment]
- **Watch - which `session/opened` carries `parent` once a restart drops the witness (span=57e1dd88753a)**: accepted-and-deferred
> Correct observation: a slot's logs hold one `session/opened` per create and per re-attach, and a re-attach after a gateway restart carries no `parent` because the mint witness is process-local (the fix for GPT span db37e66c9e96 on the previous head). The extraction rule is now pinned where the reader will be built: #11484's deliverable list carries it verbatim -- the fold takes `parent` from ANY `session/opened` of the slot that carries one, across every crew log the slot wrote; entries in one slot cannot disagree (one creator, stamped once at mint) and an entry without `parent` never retracts it -- together with the test shape (create -> re-attach -> restart -> re-attach folds to the same parent). That is the second clearing condition the item names.
> Not pushed into this PR's spec text now because the rule is a reader-side contract and this PR ships no reader; landing it with the reader keeps rule and test in one change, and avoids re-rolling every lane on a doc-only push.

**Comment by chenmingwei23** [comment]
**CI note (head e6585e001c): `Backend Tests (Windows) (2)` is red on one test this PR does not touch, inherited from main.**

`test/test_backend_cards.py::test_every_capability_set_is_classified_by_the_card` -- `these capability sets are not classified in agent_sdk/backend_cards.py: ['ACP_BACKENDS_SELF_SERVED_ACP']`. It fails the same way on a clean detached checkout of `origin/main` (0d6675c4ec) with nothing from this branch applied: #11431 (capability cards) and #11428 (self-served harness launch record) landed on main without the classification. The fix is #11632 (`fix(agent_sdk): classify ACP_BACKENDS_SELF_SERVED_ACP as off-card`); this branch will be rebased once it lands.

The earlier six `test_session_control` / `test_member_session_control` reds are gone since the rebase onto #11593.

**Comment by chenmingwei23** [comment]
**CI note (head e6585e001c): `Backend Tests (Windows) (1)` is red on `test/test_acp_launch_goldens.py` (10 node ids, all `TypeError: _stub_common.<locals>.<lambda>() got an unexpected keyword argument 'forward_ssh_auth_sock'`), inherited from main.**

The same 10 fail on a clean detached checkout of `origin/main` (e054b09968): #8104 added the `forward_ssh_auth_sock` launch argument and the goldens' stub lambda was not widened. The fix is #11649 (`fix(test): derive the launch-capture stubs from what they stub`). This PR touches neither file.

#11632 has landed, so the `test_backend_cards` red noted above clears on the next rebase; that rebase waits for the in-flight GPT lane on this head so any finding rides the same push.

**Comment by chenmingwei23** [comment]
- **Stale phrase in the bound's comment (span=ad587cbf686c)**: fixed
> Correct: after the lineage fix the creator id never reaches birth metadata, so `"and its birth metadata"` in `validation.py`'s comment described a store that no longer exists. Head 8328ed98d7 rewords it: the constant bounds the native-child rosters and the in-memory frozen creator id, which is the only path to `parent.sid`. Comment-only change.

**Comment by chenmingwei23** [comment]
- **Item 1 - zero consumers of `parent` (span=1cff710dbd6d)**: accepted-and-deferred
> Same item and clearing condition as spans ac6961f64e8c, 35b8ee63139a, fd4a24a07494 and a0da6cceff95 on earlier heads: the consumer is #11484 (label deferred-finding, assignee chenmingwei23, Due 2026-10-01), whose deliverable list names the fold keyed by `parent.slot`, the extraction rule across a slot's opened entries, and the test shape; the body's Related Issues carries `Part of #11484`. Producer-first is the only order available because the child's id does not exist when `session_create` runs.

**Comment by chenmingwei23** [comment]
- **Item 2 - zero consumers of `sid` (span=8e90e2184f8d)**: accepted-and-deferred
> The named reader exists in #11484's deliverable list: the projection resolves `parent.sid` to the creator's crew log path so a System page row links to the exact creator log, which the slot cannot do once its slot key has been recycled onto a later ACP session. It is deferred with the tree reader rather than subtracted because the sid cannot be added later: the creator handle may be replaced after mint (the GPT finding fixed on head 545405ed20), so the id is either captured at mint or lost. The retrospective after round 4 (issuecomment-5721674342) carries the Watch item that if #11484 drops the sid consumer, the sid half and its bound go together.

**Comment by chenmingwei23** [comment]
- **Watch - which `session/opened` the fold reads when entries disagree on `parent` (span=4faa9219c479)**: accepted-and-deferred
> Same item as span 57e1dd88753a on head e6585e001c, same answer: the rule is pinned in #11484's deliverable list, where the reader is built -- the fold takes `parent` from ANY `session/opened` of the slot that carries one, across every crew log the slot wrote; entries in one slot cannot disagree (one creator, stamped once at mint) and an entry without `parent` (a re-attach after a gateway restart, where the mint witness is gone) never retracts it. The issue also carries the test shape (create -> re-attach -> restart -> re-attach folds to the same parent), which is the item's second clearing condition.
> Kept out of this PR's spec text because it is a reader-side contract and this PR ships no reader; if this branch needs another push for any other reason, the two sentences ride along.

**Review by bolichen97 — APPROVED** [review]
Approved
