### ISSUE TITLE
Flaky on CI: link-time backfill options control never posts (test_replayed_options_are_a_control_not_literal_text)

### ISSUE THREAD

**Issue by chenmingwei23** [kirodotdev/KiroCrew#4076]
## What is the problem?

`test/test_slack_options_lifecycle.py::TestLinkTimeBackfill::test_replayed_options_are_a_control_not_literal_text` fails intermittently on CI Linux shards with:

```
blocks = state.slack_client.post_blocks.await_args.args[1]
AttributeError: 'NoneType' object has no attribute 'args'
```

i.e. the link-time backfill never called `post_blocks` at all -- the replayed `[OPTIONS:]` assistant row was not rendered as a Block Kit control.

## Evidence that this is pre-existing and CI-timing-dependent

- It failed on a **main** CI run with no related change in flight: run 31969535671 (1 hit for this test in its failed logs).
- On PR #4026 it failed twice consecutively (run 31997118162 attempts 1 and 2, Backend Tests 3.12 shard 4), identical assertion both times.
- It does NOT reproduce locally: 6/6 green in isolation (`-n0`), and green inside the exact CI shard composition (`pytest --splits 4 --group 4` on the same branch, 13727 passed).

The frequency uptick on the PR is plausibly pytest-split rebalancing: new tests absent from `.test_durations` get the average duration, shifting shard-4's composition and therefore the xdist worker interleaving this test runs under.

## Where to look

The backfill pipeline (`chat_slack.py` link-time drain -> `asyncio.to_thread(select_backfill_messages, ...)` -> `_post_options` -> `post_blocks`). `post_blocks` never being awaited means either `selection.messages` came back empty or the OPTIONS row was not classified as an agent-authored control candidate on that run -- both point at state shared across tests in the same xdist worker (module-level options registries keyed on the widely reused `dashboard:s1` session key are one candidate) or at the transcript-read fallback inside `select_backfill_messages` behaving differently under CI load.

Per the repo's testing conventions, this needs a root-cause fix (seed/poll/isolate), not a rerun or a relaxed assertion.

**Comment by chenmingwei23** [comment]
Kiro Crew Auto-Pipeline [operator: chenmingwei23]: Routed to needs-investigation. This is a CI-timing-dependent flake with two plausible root causes and no local repro, so it needs a diagnosis pass rather than a mechanical patch. Where a human should look: (1) module-level OPTIONS registries keyed on the widely-reused dashboard:s1 session key - cross-test state bleed within one xdist worker would leave selection.messages empty so _post_options never calls post_blocks; (2) the transcript-read fallback inside select_backfill_messages under CI load. Reproduce by forcing shard-4's xdist worker composition (pytest --splits 4 --group 4 after perturbing .test_durations) rather than isolated runs. Per repo conventions the fix must seed/poll/isolate, not rerun or relax the assertion.

**Comment by leonlaiyc** [comment]
This appears resolved by #4189 (`668b0eb2a`), which now deterministically awaits the link-time Slack backfill before these assertions rather than relying on a scheduling window.

`test_replayed_options_are_a_control_not_literal_text` drains via `drain_background_tasks(state)` on current `main`, as does every other case in `TestLinkTimeBackfill`. Verified against `fa6261c4f`: the class is 7 passed.

Same root cause as #4123. This issue can likely be closed.

**Comment by bolichen97** [comment]
Closing as fixed by #4189 (`668b0eb2a`, merged 2026-08-17) — same root cause as #4123: the endpoint scheduled the link-time backfill fire-and-forget and the test asserted before the task ran. #4189 awaits the backfill deterministically, so the replayed `[OPTIONS]` control is posted before the assertion reads it. Confirmed by @leonlaiyc above.

[operator: bolichen97]
