### PR TITLE
fix(test): stop kill_and_reap's group-kill skip from reading host process state

### PR DESCRIPTION
**Pull request by iamwhatever**
## Problem / Motivation

Four backend tests failed together in one run and passed on re-run:

```
FAILED test/test_source_providers.py::test_run_json_kills_process_tree_when_stdout_exceeds_limit
  - assert [] == [(4242, <Signals.SIGKILL: 9>)]
FAILED test/test_source_providers.py::test_terminate_process_reaps_via_communicate_not_wait
FAILED test/test_update_provider.py::TestCancellationKillsUpdaterChild::test_kill_and_reap_kills_the_whole_tree
  - Expected mock to have been awaited once. Awaited 0 times.
FAILED src/kiro_crew/apps/builtins/ops_mission_control/tests/test_providers.py::TestRunGhTimeoutReapsChild::test_timeout_reaps_child_via_communicate_not_wait
  - Lists differ: [] != [(4242, <Signals.SIGKILL: 9>)]
```

Each asserts that `platform_compat.kill_and_reap()` SIGKILLs the child's whole
process group. Each hands it a **synthetic pid** (4242, the shared convention in
this suite) with the tree kill mocked.

But `kill_and_reap` decided whether to send the group signal by asking the **live
process table**: it skips the group kill when `os.getpgid(pid)` matches the
gateway's own pgid, because a child spawned without `start_new_session` leads no
tree of its own and would otherwise trip `kill_process_tree`'s broadcast refusal
on every routine timeout.

So the assertion was at the mercy of whichever real process happened to own pid
4242. When that pid belonged to a live process **inside the pytest run's own
process group** — and under xdist the runner spawns plenty of low-pid children in
exactly that group — the skip fired, no tree kill was recorded, and every one of
those tests failed at once. That batch shape (four tests, three files, one run,
green on re-run) is the fingerprint.

## Why it matters

A flake that fires in batches across three files reads as a real regression in
process cleanup, so it costs a triage pass every time it lands, and it teaches
the habit of re-running red CI instead of reading it. The same synthetic-pid
assertion also sits in two sites that had not flaked yet — `TestKillAndReap` in
`test/test_platform_compat.py` and `TestReapInstallTree` in
`test/test_mcp_resolve_once.py` — so the blast radius grows with every new test
of this path.

## What changed (motivation → approach → change)

**Symptom** — four tree-kill assertions fail together, green on re-run.
**Root cause** — the same-group probe inside `kill_and_reap._cleanup()` reads the
host process table, so a fake pid resolves against whatever really owns it.

The probe becomes a named seam, `_shares_own_process_group()`, and the rootdir
`conftest.py` pins it for the whole suite to the child-leads-its-own-group answer
— i.e. *attempt* the tree kill — which is what every affected test is written to
assert. Same class of floor as that conftest's existing pins (the XDG home, the
sandbox mount-source roots, the /proc pin scan): a test seam that reads host
state and that each test had to remember to stub.

Behaviour is preserved on every production path. Non-POSIX returns `False`,
matching the old `IS_POSIX`-gated `same_group = False`; a probe exception returns
`False`, matching the old `contextlib.suppress(Exception)` leaving `same_group`
false. Both mean *signal the tree*, exactly as before.

**Why pin this function and not `_OWN_PGID`.** The skip is an optimisation, not
a safety guard. The guard is `kill_process_tree`'s own broadcast/self-pgid
refusal, which this change does not touch: a **real** same-group child reached
through the fixture is still refused a group signal and still falls through to
the pid-scoped kill. Pinning the shared `_OWN_PGID` instead would have disarmed
that refusal — the thing standing between a test double and a signal broadcast
to the whole pytest run.

## Tests

- `TestKillAndReap::test_skips_the_group_kill_for_a_same_group_child` — the skip path had **no test at all** before this PR. Locks in that a same-group child gets no group signal and is still covered by the pid-scoped kill, and doubles as the documented escape hatch from the autouse pin (a test that wants the skip patches the seam itself and wins).
- `TestKillAndReap::test_group_probe_reports_our_own_group` — the probe answers `True` for our own pid.
- `TestKillAndReap::test_group_probe_fails_closed_for_an_unreadable_pid` — a `ProcessLookupError` yields `False`, so a vanished pid still gets its tree signalled.
- `TestKillAndReap::test_group_probe_is_posix_only` — on Windows the probe never reaches `os.getpgid`.

The real probe is bound at module import (`_real_shares_own_process_group`),
before the autouse pin replaces the module attribute — otherwise these three
would exercise the stub.

## Manual verification

The flake was reproduced deterministically rather than argued from the traceback.
A throwaway pytest plugin forced the probe's `os.getpgid` to return `_OWN_PGID`
— simulating a real process owning pid 4242 inside the runner's group:

- **On this base, without the fixture:** all four reported tests fail, with the exact assertions from the report.
- **With the fixture:** all four pass, as do the two latent sites.

Full backend suite run twice under `-n 8`, once on this branch and once on clean
`origin/main`: **97 failures on each side**, all pre-existing host-isolation
artifacts of running outside CI (real-home pinning, `AF_UNIX path too long`,
worker-budget counts that assume CI's core count). The sets differ by one flake
in each direction — a `/tmp/x` ordering artifact in
`test_deploy_round3_fixes.py` on this side (passes in isolation on both) and a
slot-cap timing test on the base side — and neither is touched by this change.
A later diff-scoped `run_scoped_tests.py --surface backend` run (escalated to the
full suite, correctly, because `conftest.py` is a broad-impact change) produced a
failure set that is a **strict subset** of that clean-`main` baseline: zero
branch-only failures.

## Screenshots / video

N/A — backend and test-harness only, no user-visible surface.

## Related Issues

no linked issue: the flake was reported directly from a CI run, not filed.

## Checklist

- [x] At most two commits (one is the norm), with a Conventional Commits title (`feat|fix|docs|refactor|perf|test|chore|ci|build|revert: ...`)
- [x] Existing tests pass and new tests added for new functionality
- [x] Self-review completed; code follows project style guidelines
- [x] Documentation updated (if applicable) — the reasoning lives in the docstrings of the new seam and the new fixture, which is where a future reader of this code path looks
- [x] No secrets, credentials, or internal references in the diff

### CODE REVIEW

**Comment by iamwhatever** [comment]
`TestKillAndReap::test_group_probe_is_posix_only` is failing on the **Windows** shard, and it is deterministic there rather than a flake — worth fixing before this lands, since the test only exists on this branch.

```
FAILED test/test_platform_compat.py::TestKillAndReap::test_group_probe_is_posix_only
  - AttributeError: <module 'os' (frozen)> has no attribute 'getpgid'
=== 1 failed, 16873 passed, 1339 skipped, 874 warnings in 801.26s ===
```

The raiser is the test's own arrangement, not the code under test: that message is `monkeypatch.setattr`'s own `AttributeError("%r has no attribute %r")`, and `os.getpgid` is Unix-only, so on Windows the patch target does not exist. The two sibling probe tests are `@pytest.mark.skipif(not pc.IS_POSIX)`, which is why only this one — the deliberately cross-platform one — is red. The 1339 skips vs ~549 on the Linux shards is the giveaway for which lane it is.

One-line fix that keeps the test's whole point (that the probe never reaches `os.getpgid` when `IS_POSIX` is false), and works on both platforms — on Windows the sentinel is created, never called, and removed at teardown:

```python
    def test_group_probe_is_posix_only(self, monkeypatch) -> None:
        monkeypatch.setattr(pc, "IS_POSIX", False)
        monkeypatch.setattr(
            pc.os,
            "getpgid",
            lambda _pid: (_ for _ in ()).throw(AssertionError("probed on Windows")),
            raising=False,
        )
        assert _real_shares_own_process_group(os.getpid()) is False
```

`raising=False` is the minimal change; adding `skipif(not pc.IS_POSIX)` instead would delete exactly the platform this case is written to cover.

Nothing else in the diff has the same hole: the conftest fixture pins `platform_compat._shares_own_process_group` rather than reaching into `os`, and `test_skips_the_group_kill_for_a_same_group_child` patches module attributes only.

**Comment by iamwhatever** [comment]
Pushed `4a0de1ddf` (amended, still one commit) with the `raising=False` fix from the comment above — the Windows shard failure was in this branch's own new test, not in the code under test.

Proof, on Linux, by simulating the platform (`monkeypatch.delattr(os, "getpgid")` first):

- old strict form → `AttributeError` raised at the `monkeypatch.setattr` line, exactly the CI failure
- `raising=False` form → sentinel installed, never called, `_shares_own_process_group(os.getpid())` returns `False`

`test/test_platform_compat.py` locally: 256 passed, 23 skipped, and the two `ps`-related failures (`test_parent_map_ignores_a_planted_ps_earlier_on_path`, `test_process_descendants_snapshots_a_new_session_grandchild`) reproduce identically on pristine `origin/main` in this sandbox, so they are environmental and not from this diff. Black / isort / flake8 clean. The commit body now records why this one case is deliberately not `skipif`-guarded.

**Review by bolichen97 — APPROVED** [review]
Tier 1 auto-approve: fix (3 files). Criteria: no conflict, no requested changes, security path denylist clean, design-doc gate clean, SAST annotations clean, security checklist all-NO, AI reviewers green. Category: fix a POSIX flake by extracting kill_and_reap's same-group probe into a named seam a test can pin; the kill_process_tree broadcast refusal is untouched.

**Review by bolichen97 — APPROVED** [review]
Tier 1 auto-approve: fix (3 files). Criteria: no conflict, no requested changes, security path denylist clean, design-doc gate clean, SAST annotations clean, security checklist all-NO, AI reviewers green. Category: clear root cause -- kill_and_reap's group-kill skip probed the live process table against synthetic test pids, causing batch flakes; the probe is extracted to a named seam with identical fail-closed semantics and pinned in tests.
