### PR TITLE
fix(knowledge): run the duplicate-skip gate off the event loop

### PR DESCRIPTION
**Pull request by CrysisDeu**
# Problem

The gateway crash-loops every 6–8 minutes while the knowledge folder watcher
scans. Ten loop-stall dumps landed in one hour on a build that already carries
the earlier off-loop fixes, every one with `delete_items_batch` on the main
thread. The user-visible symptom is the app dying and relaunching repeatedly,
each relaunch re-paying full startup.

# Why it matters

A stalled event loop freezes every task on it — the user's chat turn and the
liveness heartbeat alike — so the watchdog kills the process and the supervisor
respawns it into the same scan. That is a self-sustaining loop, not a one-off
hitch: the app is never reliably usable while a source with duplicate content
is being scanned.

# Fix (symptom → root cause → change)

The earlier pass wrapped the five `delete_items_batch` sites reachable from the
ingest body, but `_skip_as_duplicate` was missed. It is a **sync** method called
bare from two `async def`s (`ingest_file`, `ingest_text`), and it deletes the
superseded items at `ingestion.py:217` directly on the loop.

Why that delete is expensive: `delete_items_batch` does not just delete. After
the per-item cascade it re-runs the orphan-entity sweep — three `NOT IN`
subqueries over the mention and relation tables — and then calls `_load_graph()`,
a **full** rebuild of the entity graph. On a large library that is seconds of
blocking SQLite, paid per duplicate file the scan meets.

The change routes the gate through the existing `run_to_completion` helper, so
the delete, the source-location attach and the terminal job row travel as **one**
hop. That grouping is deliberate and load-bearing: splitting the committed delete
from the row that records it strands data, because the next scan then re-ingests
alongside the orphaned items — the same hazard the helper was introduced for.

`run_to_completion` is widened to forward its callable's return value
(`Callable[[], _T] -> _T`). The gate reports a job id its callers branch on;
with the old `-> None` signature that value would have to be read after the
await, splitting the very unit the hop exists to keep whole. Cancellation
semantics are unchanged — the work is still drained and the `CancelledError`
still wins; only the value is dropped. Backward-compatible for the two existing
`None`-returning finalizers.

**Scope note, stated plainly:** this makes the gateway *survive* the scan. It does
not make the work *cheap* — a full graph rebuild after deleting a handful of items
is a separate defect, and each duplicate file still burns that cost on a worker
thread. Incremental graph maintenance touches every mutation path and belongs in
its own change, not smuggled into a crash-loop fix.

# Tests

Two added to `test/test_knowledge_delete_off_loop.py`, alongside the existing
AST ratchet and off-thread assertions:

- `test_duplicate_skip_runs_the_delete_off_the_loop_thread` — records the thread
  ident inside a wrapped `delete_items_batch` and asserts it is **not** the loop
  thread. It also asserts the gate was actually reached, so the test cannot pass
  vacuously if the duplicate path is skipped.
- `test_run_to_completion_forwards_the_return_value` — pins the widened
  signature, which is what lets the mutation and its reported value stay in one
  hop.

# Manual verification

N/A — unit coverage is sufficient. The defect is "which thread runs this call",
which the off-thread assertion checks directly and the AST ratchet prevents
regressing. Reproducing the crash loop itself needs a multi-thousand-file corpus
with duplicate content and a live watchdog, which no unit test should carry.

# Screenshots

N/A — no user-visible UI change.

### CODE REVIEW

**Comment by CrysisDeu** [comment]
## Disposition — GPT 5.6 finding on `1c4a84cca`

**BLOCKING — `ingestion.py:436` — "Duplicate gate races holder deletion" → FIXED** in `d4fe1a461`.

The finding is correct, and it is worth stating precisely why, because the
mechanism is subtle. While `_skip_as_duplicate` ran on the event loop it had no
`await` in it, so it was atomic against every other coroutine *by construction* —
a user's `delete_source_cascade` could only land before or after it, never inside.
Moving it to a worker thread removed that accidental guarantee. The dashboard
already runs `delete_source_cascade` off-loop (`handlers/knowledge.py:1015`), so
after the offload two threads on two connections genuinely interleave, and the
gate's read-then-write across three separate transactions became a real TOCTOU.
Consequence as reported: the target gets a terminal `skipped_duplicate` row while
the copy it attached to is cascaded away, and the content is unrecoverable.

**What was NOT done, and why.** The suggested remedy — "revert both offloads until
the gate is atomic with source deletion" — was not taken. Reverting restores the
loop-stall crash loop this PR exists to fix, which trades data loss for a gateway
that dies every 6–8 minutes. Instead the gate was made atomic, which satisfies the
same precondition without giving up the fix.

**The fix.** The gate now runs as ONE `BEGIN IMMEDIATE` transaction that re-reads
the holder *under the write lock* and declines to dedupe when it is gone, falling
through to a normal ingest. This is the idiom already used in this codebase for
exactly this hazard — `delete_source_cascade` (`store.py:954`) and
`start_rebuild_job` (`ingestion.py:983`, whose comment says a concurrent writer
"can't both observe" the pre-state). A concurrent `delete_source_cascade` now
waits on the lock instead of racing. A cheap unlocked probe runs first so the
common not-a-duplicate answer does not serialize every ingest behind the lock.

Two seams were needed to make that possible without touching existing callers:

- `delete_items_batch` keeps its own transaction and graph reload, but delegates
  its body to a new `delete_items_batch_in_txn`, so a caller already holding a
  write transaction can include the delete in it. The five sites from #2336 are
  unchanged.
- `add_source_location` grows an `_in_txn` variant. This one is load-bearing and
  easy to miss: the connection is in autocommit mode, so its trailing
  `db.commit()` would have **ended the caller's `BEGIN IMMEDIATE` early** and
  reopened the very window the lock closes.

**Regression test, proven red pre-fix.**
`test_duplicate_gate_reingests_when_the_holder_vanishes_before_the_lock` makes the
authoritative in-transaction lookup miss after the probe has hit, and asserts the
target is *not* recorded as a duplicate and keeps items of its own. Stripping the
in-transaction revalidation makes it fail with
`the gate consulted the holder only once, so the holder is still read outside the
write lock` — so it cannot pass vacuously. The pre-existing off-thread test was
retargeted to the `_in_txn` seam the gate now calls; its own non-vacuous guard
caught that retarget being necessary.

Verified locally: 264 passed across the knowledge suite, `isort` / `flake8` /
`mypy` clean, rebased onto current `main`.

---

### Also on this PR, for the record

**`Backend Tests (Windows) (2)` — unrelated, not fixed here.** It fails on
`test_lesson_contradiction.py::test_a_sharp_s_case_variant_inserts_rather_than_enriching`
(`stored spelling lost: ['STRASSE …']`), a German ß→SS casefold issue in **lesson**
storage. That test is `main`'s own (from #2166) and untouched by this branch, its
only "knowledge" reference is a category *string*, and neither `vector_memory.py`
nor `lessons.py` imports `knowledge.ingestion` — so no code path connects it to
this diff. `main`'s Windows shard also fails independently (3 of its last 8 CI runs
red, most recently on a different test entirely).

**Cost, acknowledged and deferred.** Off-loading makes the gateway *survive* the
scan; it does not make the work *cheap*. `delete_items_batch` still runs a full
`_load_graph()` rebuild plus the orphan sweep per call, now on a worker thread.
Incremental graph maintenance touches every mutation path and is deliberately not
in this PR.

**Comment by CrysisDeu** [comment]
## Parking this PR — the approach is wrong for this site

Converting to draft. Not because GPT's findings are wrong (they are both correct), but
because the strategy cannot succeed, and the evidence for that is empirical rather than
argumentative.

**The decisive fact.** #2336 is merged and shipped, this PR's site is the last one it
missed — and the gateway still wrote a loop-stall dump two minutes before this comment.
The crash moved to `folder_watcher.py:830`, an unrelated `SELECT id FROM items WHERE
source_id = ?` that returns 20,003 rows in ~1.1s per file on the affected corpus. At a
15s watchdog that is ~13 files to death. So even merged and green, this PR does not stop
the crash loop it was written for.

**Why site-by-site off-loading cannot win here.** On a 20k-item source, *every*
synchronous sqlite call on the ingest path is a bomb, and there are many. Worse, each
off-load has a cost the first ones hid: `_skip_as_duplicate` was atomic against every
other coroutine purely because it contained no `await`. That guarantee was free, it was
never designed, and moving the function to a thread spends it. GPT found the resulting
race twice, at two different boundaries:

1. holder deleted between the probe and the attach → fixed here with `BEGIN IMMEDIATE`
   plus revalidation;
2. the caller's `folder_file_state` finalization sits outside that serialized unit →
   would require the transaction to span `ingest_file`'s return.

Round 2 is not a defect in the round-1 fix. It is the next step that was also implicitly
atomic. There is no reason to expect it is the last one, and both times the reviewer's
own remedy was "revert the offload" — which trades data loss for a crash loop.

**What actually fixes it.** Two things, neither of them this PR:

- *Make the work cheap instead of moving it.* `delete_items_batch` ends in a full
  `_load_graph()` — a complete rebuild of a 175k-node / 250k-edge graph after deleting a
  handful of items — and re-runs the orphan sweep that `_init_schema` already runs. Make
  the graph update incremental and gate the sweep behind an `EXISTS` probe, and the
  ~2.3s becomes milliseconds. Cheap work does not need to leave the loop, so all the
  free atomicity is preserved and none of these races exist.
- *Stop the corpus from being created.* #1380 auto-registers chat-slot project
  directories with a `max_files` cap but no chunk-count budget and no worktree dedup. A
  directory holding 73 git worktrees produced a single 20,356-item source without the
  user doing anything. A file-count cap does not bound chunk count, which is the
  quantity that actually hurts.

**What is worth keeping from this branch.** `delete_items_batch_in_txn` and
`add_source_location_in_txn` are the seams any atomic version of this path needs, and the
second one documents a real trap: on this autocommit connection, `add_source_location`'s
trailing `db.commit()` silently ends an enclosing `BEGIN IMMEDIATE`. Also
`run_to_completion` forwarding its return value. Whoever picks up the incremental-graph
work should lift those rather than rediscover them.

No override requested. GPT is flagging real data loss, and "accept stranding items to
stop a crash loop" is a bad trade when making the delete cheap avoids both.

**Comment by CrysisDeu** [comment]
Round 2 disposition, and why this is out of draft again.

**BLOCKING — `ingestion.py:265` — "the holder lock is released before duplicate state finalization" → FIXED** in `36e31d4b5`.

The finding is correct, and the mechanism is worth stating precisely. The gate commits its own `BEGIN IMMEDIATE` before returning, so a user deleting the HOLDER lands in the window between that commit and the scan's terminal state write. That cascade is not destructive on its own — it sees this folder's `source_locations` row, reassigns the surviving item to this source, and adopts it into this very `folder_file_state` row. What destroyed the document was the write that came next: `item_ids='[]'`, which is what "the gate refused, so this file owns nothing" predicts. That erased the adoption and left the only remaining copy owned by the source but named by no state row — unreachable by the deleted-file path and undeletable, exactly the strand the ownership model exists to prevent.

**What was NOT done, and why.** The suggested remedy — revert the off-loop gate hunk — was not taken, for the same reason as round 1: reverting restores the loop-stall crash loop this PR exists to fix, trading data loss for a gateway that dies every 6–8 minutes. Nor was the alternative I had written off in my own parking note taken: making the transaction span `ingest_file`'s return. That would hold the write lock across an LLM extraction call.

**The fix.** `FolderWatcher._record_deduped_state` takes the same `BEGIN IMMEDIATE` and **reads** the file's item group instead of assuming it empty, writing the healthy status when items are there. That is enough, because it removes the ordering assumption rather than trying to eliminate the ordering:

- cascade lands *before* this read → its adoption is visible, and preserved;
- cascade lands *after* → the row now exists with the matching hash, so the cascade's own `_adopt_reassigned_item` step fills the group in (the path already designed for this);
- cascade lands *during* → serialized by the lock.

There is no interleaving left in which the terminal write can contradict the database. Two short transactions do the job; one long one is not needed.

Mechanically the change also splits `_update_state` into `_write_state_row` (no transaction control, reusable inside a lock) plus the commit, and lifts the refused-row text-hash derivation into `_deduped_text_hash` so both paths share it. No behavior change on the `done` / `failed` / `scanning` writes.

**Regression test, proven red pre-fix.** `test_deduped_state_write_keeps_an_adoption_that_landed_after_the_gate` reproduces the interleaving deterministically with no threads: it wraps `pipeline.ingest_file` and cascades the holder away the instant the gate returns its terminal job, then asserts the state row names the items the source now owns. Replacing the in-lock read with a predicted `[]` fails it with `the terminal 'deduped' write overwrote the adoption: this source owns ['11c9f139-…'] but its state row names []`. Two non-vacuity guards sit in front of that assertion — one that the gate actually refused the file, one that the cascade actually left this source owning something — so it cannot pass for the wrong reason.

Verified locally after rebasing onto `0f1a4d55a` (one additive conflict in `ingestion.py`, main's `EmbedRateLimiter` alongside this branch's `_T`): 1174 tests pass across the knowledge, folder, dedup and ingest suites; `isort`, `flake8`, `mypy`, `docs-lint` all exit 0. `docs/system-specs/modules/knowledge.md` is updated in the same commit — its pre-ingest-gate bullet said the state row "is then recorded with an empty group", which is no longer unconditionally true.

**On the parking note above.** I wrote that this strategy could not win because round 2 would not be the last implicitly-atomic step. I still think the two things named there are the real fixes — make `delete_items_batch` cheap so the work never has to leave the loop, and stop a 20k-item source from being created in the first place — and this PR is still not a fix for the crash loop that has since moved to `folder_watcher.py:830`. What changed my mind about *this* PR is the shape of the remedy: rounds 1 and 2 were both closed by the same rule, take the write lock and derive the state rather than predict it, and applying that rule leaves the gate with no predicted state left to be wrong about. That is a closed set, not an open series.

**Comment by CrysisDeu** [comment]
Round 3 disposition.

**BLOCKING — `folder_watcher.py:513` — "duplicate-state transaction blocks the event loop" → FIXED** in `d8f6e9cfd`.

Correct, and it is a regression I introduced in the round-2 fix rather than a pre-existing property. `_record_deduped_state` was called synchronously from `_do_scan`, which is a coroutine, so its `BEGIN IMMEDIATE` acquired the write lock on the loop thread — and acquiring a write lock is a blocking wait, up to this connection's 30s timeout, on any concurrent writer. That is the exact stall class this PR exists to remove, reintroduced one line further along than the one it removed. Closing a race by taking a lock is only safe if the lock is taken somewhere it is allowed to wait.

**The fix** is the one suggested: the call now goes through `await run_to_completion(lambda: self._record_deduped_state(...))`. `run_to_completion` rather than a bare `asyncio.to_thread` for the reason this PR added the helper — a cancellation arriving while the work item is still queued in the executor drops the callable entirely, and dropping *this* callable leaves the file's row on its `scanning` marker, which is re-ingested at full cost on every later sweep. Same guarantee the gate's own delete already has.

Two notes on why this is safe rather than merely quieter:

- The store hands out one connection **per thread**, so the worker gets its own. That is what makes the lock do its job: it now serializes against the dashboard's off-loop `delete_source_cascade` instead of contending with it from the loop thread. The connection is in autocommit mode, so the loop thread holds no open transaction that the worker could deadlock against.
- The surrounding scan's other state writes (`done` / `failed` / `scanning`, `last_seen`) still run on the loop connection. With autocommit each is its own committed statement, so there is no cross-connection transaction to interleave — only this one write needs the lock, and only it leaves the loop.

**Regression guard.** Rather than add a second near-duplicate scan test, the round-2 test now also records which thread the terminal write lands on, and is renamed `test_deduped_state_write_is_off_loop_and_keeps_a_late_adoption` — both properties belong to that single write. Reverting the offload fails it with `the terminal 'deduped' write ran on the event-loop thread; it takes the write lock, so it must travel through run_to_completion`, and it carries its own "was this branch even reached" guard so it cannot pass vacuously.

Verified: 1174 tests pass across the knowledge, folder, dedup and ingest suites; `isort`, `flake8`, `mypy` all exit 0.

### The other reds on this PR, for the record — neither is from this diff

- **Inclusive Language** — infrastructure, not content: the job died in `Install woke` with `curl: (56) Connection died, tried 5 times before giving up` fetching the pinned woke release. It never scanned anything. Cleared by the re-run this push triggers.
- **Electron Shell Tests** — `mochi/test/petOverlays.test.js`, 850 pass / 1 fail. That file is the only test in its directory that does not stub `require('electron')` via a `Module._load` intercept — its six siblings all do — and the job sets `ELECTRON_SKIP_BINARY_DOWNLOAD=1`, so it passes or fails on runner cache state. This diff touches no file under `website/`. It wants the one-line intercept copied from a sibling, in a PR that owns that directory rather than this one.

**Comment by CrysisDeu** [comment]
Round 4/5 disposition — GPT and Opus converged on one root cause, and an independent review of the fix found the fix was also wrong. Pushed as `43c3976e6`.

**BLOCKING (GPT, `folder_watcher.py:733`) — "duplicate file adopts another file's item group" → FIXED**
**BLOCKING (Opus, same line) — "cross-wires one physical item into two same-content files' state rows" → SAME ROOT CAUSE, FIXED**

Both are correct and both describe the same defect: the ownership read was scoped `(source_id, content_hash)` with no `file_path`, so two byte-identical files in one folder would have the refused row named with the sibling's item. Deleting either file then runs `_delete_item_cascade` on an item the other row still names, destroying content whose file is still on disk. `_adopt_reassigned_item` guards exactly this with `len(matches) != 1`, and its docstring names the consequence; the new read bypassed it.

**The fix** is not the ambiguity guard Opus suggested, but the reason that guard exists: read the group from **this row** (`source_id` + `file_path`) and stop consulting the hash at all. There is then no ambiguity left to guard, and the whole bytes-vs-text hash question leaves the decision. Filtered to ids that still exist under this source, because the row is still carrying the pre-ingest `scanning` group whose items the gate just deleted — preserving `item_ids` verbatim, which is the literal reading of GPT's suggested fix, would leave the terminal row naming deleted items.

### An independent review of that fix found a third defect in it

Before pushing, I ran three blind adversarial reviewers (concurrency / logic / project-rules lenses) over the uncommitted fix, with the contract and none of my reasoning. All three landed on something neither AI lane raised, and it was real:

`items.content_hash` is over EXTRACTED TEXT; `folder_file_state.content_hash` is over RAW BYTES. `_adopt_reassigned_item` keys a folder row on `COALESCE(text_hash, content_hash)`, and a gate-refused row derives `text_hash` from a byte-identical **sibling** row. A lone PDF has no sibling, so the coalesce falls back to the bytes hash, the adoption matches nothing and returns without even logging — while `reassign_item_source` has already moved the item to this source. The row read therefore cannot see it. `store.py`'s own comment says this is "how ownership bookkeeping came to be inert for exactly those documents."

My round-4 docstring claimed reading the row "inherits that guard" from `_adopt_reassigned_item`. It inherits its blind spot. That sentence is gone.

I first tried to fix it with a hash fallback excluding ids other rows claim. **That does not work, and the test proved it:** `_deduped_text_hash` derives the text hash from a sibling too, so with no sibling it returns the bytes hash and matches nothing. The domains cannot be crossed without the real text hash. The fallback was removed rather than shipped as a no-op with a docstring claiming otherwise.

**Scope call:** this strand is pre-existing, not introduced here. `main` writes an unconditional `item_ids='[]'` at this site, so the row never named the item there either — this change is equivalent to `main` for transformed files and strictly better for plaintext. Round 3's broader hash lookup was an accidental partial mitigation that carried the cross-wire defect both lanes just flagged, so it is not a baseline worth restoring. Closing the gap properly needs the incoming document's text hash carried out of the gate instead of derived from a sibling, which changes what the gate reports and belongs in its own change.

It is pinned rather than described: `test_deduped_state_write_recovers_a_transformed_files_reassigned_item` is a **strict** xfail with a live repro (PDF bytes plus a reader returning different text, so the two hashes provably differ — the test asserts that inequality so it cannot silently degrade into the plaintext path). Strict means it fails the moment someone plumbs the hash through and the exemption goes stale.

### Also fixed from that review

- **Unreadable `item_ids` destroyed a recoverable value.** Mapping a JSON parse failure to `[]` let the caller overwrite the corrupt-but-recoverable list with an empty terminal group, orphaning everything it named. It now raises, leaving the row on `scanning` for the next sweep — matching how this codebase treats an unreadable store elsewhere. Test: `test_deduped_state_write_propagates_an_unreadable_group`.
- **`busy_timeout` is 10s, not 30s.** `PRAGMA busy_timeout=10000` overrides the 30s connect timeout; my round-3 comment said 30s. Corrected in the commit message.
- **`_surviving_group` docstring** now states it must never run on the event loop, matching the sibling `_dedup_ingested` convention.
- **Spec** (`docs/system-specs/modules/knowledge.md`) updated in the same commit: it said the terminal write "reads the file's item group", which is now conditional, and it did not mention either the row-scoping requirement or the transformed-file gap.

Findings I checked and rejected, with the evidence:
- `SQLITE_MAX_VARIABLE_NUMBER` on the `IN (…)` list — `chunker.MAX_CHUNKS_PER_FILE = 50` bounds the group at 50 binds, far under 999.
- `ROLLBACK` with no active transaction masking a lock-wait error — `BEGIN IMMEDIATE` is outside the `try`, matching the gate's existing pattern, so the `except` is unreachable when the lock acquisition itself fails.
- A source deleted mid-scan leaving a resurrected row — real, but a pre-existing property of every terminal write in this file (`done` and `failed` included). Fixing only the `deduped` path would be incoherent; noted, not done here.

Verified after rebasing onto `a72c985f8`: 1225 pass / 1 xfail across the knowledge, folder, dedup and ingest suites; `isort`, `flake8`, `mypy`, `docs-lint` all exit 0.

**Comment by CrysisDeu** [comment]
Round 6 disposition — accepted, and generalised to all three doc-state tables. Pushed as `2610d839d`.

**BLOCKING — `ingestion.py:336` — "Aggregate ownership state remains outside the transaction" → FIXED**

Correct, and it is the same window as round 2 in two more subsystems. Both aggregate paths wrote a hardcoded empty group after the gate had already committed:

- `agent_source.py` — `set_state(store, source_id, slug, content_hash, [], title, status="deduped")`
- `artifact_ingest.py` — `_set_state(..., [], title, status="deduped", kind=art.kind)`

Both sit in `async def` bodies (`_add_agent_document`, `ingest_artifact`), so like the folder path they needed the lock AND the hop, not just the lock.

The aggregate case is **more** reachable than the folder one, which is worth stating because it inverts the intuition that folders are the risky path: `_OWNERSHIP_HASH_COL` maps `artifact_item_state` and `agent_item_state` to `content_hash`, which is already the text-hash domain, so `_adopt_reassigned_item` genuinely matches and adopts — and then the caller clobbered it. On the folder path the same adoption often silently matches nothing for a transformed file, so there was frequently nothing there to clobber.

**Not the suggested fix.** GPT proposed bypassing the gate for `artifact` and `agent` sources until their state write could move inside the transaction. That trades a race for switching duplicate detection off on two of the three source families — the aggregates are exactly where duplicates concentrate, and `find_document_by_hash` exists because a source-level exclusion is already blind inside an aggregate.

**What landed instead.** One derivation, three thin locked wrappers:

- `KnowledgeStore.surviving_group_in_txn(table, source_id, key)` holds the whole rule — row-scoped read, filter to ids still owned by this source, raise on unreadable JSON. `_DOC_STATE_KEY_COL` names the identifying column per table (`file_path` for folders, `slug` for both aggregates) as a whitelist, since those identifiers are interpolated into SQL.
- Each of the three sites wraps `BEGIN IMMEDIATE` + derive + write and reaches it through `run_to_completion`.
- `folder_watcher._surviving_group` now delegates to the shared primitive rather than carrying its own copy, so the three paths cannot drift apart — which is the actual lesson of six rounds in one subsystem.
- An aggregate row that ends up owning items is written `active`, not `deduped`: `find_document_by_hash` only matches `active`, and a row that owns the content while reporting `deduped` would let identical text in again under a second slug. That asymmetry with folders (`done`) is why `_DOC_STATE_TABLES` carries a per-table healthy status.

**Tests, each proven red against the code it guards.**

- `test_artifact_deduped_state_write_keeps_a_late_adoption` and `test_agent_deduped_state_write_keeps_a_late_adoption` — both fail with `the terminal write erased the adoption: row names [], source owns <id>` when the derivation is replaced by `[]`.
- `test_aggregate_deduped_state_write_records_an_empty_group_when_nothing_adopted` — the common case still records `deduped` with no group, so the derivation cannot invent ownership.
- `test_deduped_state_writes_are_never_called_on_the_event_loop` — one AST ratchet covering all three modules at once, reusing the existing `_on_loop_call_sites` helper. Verified it catches a regression by name and line: reverting the agent hop fails it with `knowledge/agent_source.py:397 in async _add_agent_document`.

Verified after rebasing onto `bb4c597e5`: `test_knowledge_delete_off_loop.py` 14 pass / 1 xfail; the wider knowledge + folder + dedup + ingest + artifact + agent selection 4003 pass with 7 failures that are pre-existing and environmental — `test_artifact_source.py` / `test_artifacts_handlers.py` source-classification cases that assert a fake home under `/tmp` classifies as `copy`, while `/tmp` is an allowed root on this host (`assert ('link', '/tmp') == ('copy', '')`). Confirmed by stashing this change and re-running: the same 7 fail without it. `isort`, `flake8`, `mypy`, `docs-lint` all exit 0, and the spec is updated in the same commit to describe all three tables and the shared primitive.

**Comment by CrysisDeu** [comment]
Round 7 disposition — accepted. Pushed as `3fe24d35e`.

**BLOCKING — `ingestion.py:546` — "cancellation strands a duplicate claim behind stale state" → FIXED**

Correct, and it is caused by this PR's own fix mechanism rather than by anything pre-existing. `run_to_completion`'s docstring says it plainly: *"Cancellation still wins: the work is drained, but the value is dropped."* So the helper added here guarantees the gate finishes — committing the delete of the previous group, the location claim on the holder's items, and the terminal job row — and **then** re-raises, which skips the caller's terminal state write by construction. On `main` a cancellation could only land at an await inside `ingest_file`, before the gate had committed anything. The mechanism that made the gate reliable is what made the pairing unreliable.

The leak does not self-heal. The row keeps its pre-ingest marker, and a `scanning` row has no `text_hash`, so `detach_source_location_by_hash` short-circuits on `state["text_hash"] or ""` and returns 0 — nothing can release the claim on the holder's items. If the file is deleted before the next sweep, `_handle_deleted` takes the empty-group branch and the content is orphaned behind an undetachable claim.

**The fix is a convention this pipeline already had, applied to the branch that lacked it.** `ingest_file` has accepted an `on_committed` finalizer since before this PR, and its docstring gives exactly this rationale for the success branch:

> It runs INSIDE the finalize hop... doing it after this coroutine returns puts several awaits between the items becoming durable and the record that makes them replaceable — each one a cancellation point that strands the items unowned. Passing the write in here gives it the same run-to-completion guarantee as the delete it belongs with.

The duplicate branch never got its sibling. It does now: `on_duplicate`, threaded through `ingest_file` and `ingest_text` into `_skip_as_duplicate`, invoked after that transaction commits and inside the same drained unit. All three callers pass their own record in and the post-hoc `run_to_completion(_record_deduped_state)` calls are gone. That is narrower than "make the transaction span `ingest_file`'s return" — the transaction stays short; only the work UNIT spans the pair.

**Test.** `test_duplicate_gate_records_terminal_state_even_when_cancelled` holds the gate on its worker thread, cancels the awaiting task, releases the gate, and asserts the finalizer still ran. Reverting the `on_duplicate` invocation fails it with the message naming the consequence. It uses a `threading.Event` handshake rather than a sleep: an arbitrary delay would both race on a slow runner and block a shared xdist worker — I saw exactly that, an unrelated `test_subagent_reap_race` cancellation test failing under `-n auto` while passing 3/3 alone, which the handshake removed.

**Also in this push**

- **Inclusive Language was a real violation of mine, not the earlier infra failure.** The previous run died in `Install woke` on `curl: (56)`; this time woke installed and flagged `whitelist` in the `_DOC_STATE_KEY_COL` comment I added. Now `allowlist`. I re-checked the added `.py`/`.md` lines for the whole flagged set and there are no others.
- **Four test doubles updated.** `ingest_file` genuinely gained a parameter, and the fakes in `test_knowledge_folder_cost_guards.py` and `test_knowledge_agent_source.py` raised `TypeError: got an unexpected keyword argument 'on_duplicate'`. They now absorb `**kw`, so a future pipeline parameter does not break them again.

Verified after rebasing onto `3c7cbf823`: 4004 pass, 1 xfail, and 7 failures that are pre-existing and environmental (`test_artifact_source.py` / `test_artifacts_handlers.py` assert a fake home under `/tmp` classifies as `copy`, while `/tmp` is an allowed root on this host — `assert ('link', '/tmp') == ('copy', '')`; confirmed by stashing this change and re-running). `isort`, `flake8`, `mypy`, `docs-lint` and the brand gate all exit 0.

**Comment by CrysisDeu** [comment]
Round 8 disposition — accepted, and it simplifies the change. Pushed as `c27ded556`.

**BLOCKING — `ingestion.py:337` — "New aggregate documents can lose ownership across the commit gap" → FIXED**

Correct. Round 7 put the caller's record inside the gate's *hop* but still after its `COMMIT`, in its own `BEGIN IMMEDIATE`. For a FIRST-TIME artifact or agent document that is not enough: at commit time the state row does not exist yet, so a `delete_source_cascade` acquiring the lock in the gap reassigns the surviving item to this source and has nothing to adopt it into — `_adopt_reassigned_item` matches on `(source_id, content_hash)`, finds no row, and returns without logging. The record that follows then reports an empty group while the source owns a searchable item, which is the same strand one ordering earlier.

**The fix is the suggested one, and it makes the code smaller.** `on_duplicate()` now runs before the gate's `COMMIT`, and the three finalizers drop their own `BEGIN IMMEDIATE` / `COMMIT` / `ROLLBACK` blocks entirely — they are called from inside the gate's transaction, on the gate's worker thread, so they take no lock of their own. The delete of the previous group, the location claim on the holder's items, the terminal job row and the caller's record are one atomic unit. A cascade now sees either no claim at all or a claim WITH the row that names it, and there is no gap left to land in.

Two properties come free from that ordering rather than needing their own guards:

- A failure in the record rolls the whole refusal back. Previously a raising finalizer left the delete and the claim committed.
- The transaction still does not span `ingest_file`'s return. It stays inside `_skip_as_duplicate`; only the callback is injected. That is the distinction that makes this different from the "hold the write lock across an LLM extraction" shape I rejected earlier — the callback is one row read plus one `INSERT OR REPLACE`, bounded and I/O-free.

**Test.** `test_duplicate_gate_and_terminal_state_are_one_transaction` asserts atomicity directly: it makes the finalizer raise and requires the gate's delete, its claim on the holder's items, and its `skipped_duplicate` job row to all be absent afterwards. Moving `on_duplicate()` back after `COMMIT` fails it. I replaced the round-7 cancellation test with this one — it covers the same guarantee more strongly (atomic pairing rather than "the finalizer ran"), and it does so without holding a worker thread on an event, which is a real hazard: the earlier version's blocked thread perturbed an unrelated `test_subagent_reap_race` cancellation test under `-n auto` while passing 3/3 alone.

The `_record_deduped_state`-on-the-loop ratchet stays, with its rationale updated: a direct call from a coroutine body would now both take the write lock on the loop AND sit outside the gate's transaction.

### The remaining red on this PR is a main-side breakage, not this diff

`Backend Tests` shard 3 fails on 3.10, 3.12 and Windows alike — deterministic, not a flake — on `test/test_mcp_core_more_coverage.py`:

```
AttributeError: <module 'kiro_crew.mcp_core'> does not have the attribute 'is_tool_cancelled'
AttributeError: <module 'kiro_crew.mcp_core'> does not have the attribute 'resolve_max_subagents'
```

Those symbols now live in `mcp_shared.py:127` and `subagent.py:813`, and the test still `monkeypatch.setattr`s them on `mcp_core`. Checked out `origin/main`'s own copies of `test_mcp_core_more_coverage.py` and `mcp_core.py` into a clean tree and ran them: **15 failed, 96 passed**. So this arrived with the mcp_core split and this branch only inherits it by rebasing onto that main. `Coverage Gate` and `PR Readiness` are downstream of it.

Nothing in this diff touches `mcp_core`, `mcp_shared` or `subagent`, so it is not fixable here without unrelated scope. It needs its own change — pointing those monkeypatches at the modules that now own the symbols.

Verified after rebasing onto `017a78e9c`: `test_knowledge_delete_off_loop.py` 16 pass / 1 xfail; `isort`, `flake8`, `mypy`, `docs-lint` all exit 0; no inclusive-language violations in the added `.py`/`.md` lines.

**Review by bolichen97 — APPROVED** [review]
Tier 1 auto-approve: fix (10 files). Criteria: no conflict, no requested changes, no security surface, AI reviewers green. Category: knowledge subsystem — move duplicate-skip gate off the event loop.

**Review by iamwhatever — APPROVED** [review]
Tier 1 auto-approve: small-fix (10 files). Criteria: no conflict, no requested changes, no security surface, AI reviewers green. Category: moves a blocking duplicate-skip check off the event loop to prevent knowledge ingest stalls — pure async correctness fix, no behavioral change.
