### PR TITLE
fix: report an unbuildable sandbox as itself, not a missing Kiro CLI

### PR DESCRIPTION
**Pull request by darko-mesaros**
## Description

**Problem.** On a host that cannot construct the Linux namespace sandbox, the dashboard tells the user to **"Install Kiro CLI"** — on a host where `kiro-cli --version` returns `kiro-cli 2.16.0` and `kiro-cli whoami` returns `Logged in with GitHub`. The binary is present, executable and authenticated. The message is wrong, and the button it offers cannot fix anything.

**Root cause.** Verifying an *unverified* Kiro CLI runs the binary **inside the sandbox** (`_UNVERIFIED_SANDBOX_MODE = "strict"`). When the sandbox cannot be built, `wrap_argv()` fail-closes, the version probe never succeeds, no `installed=True` path is reached, and `PrerequisiteStatus.installed` keeps its dataclass default of `False`. `_probe` never reads `ProcessResult.error`, so the genuinely good tailored message `wrap_argv` already composed is discarded. Two categorically different conditions — "no binary" and "binary present but unverifiable" — collapse into one.

Ubuntu >= 23.10 with `kernel.apparmor_restrict_unprivileged_userns=1` is the common case. After #1138 the probe reports such hosts honestly, which is what makes this distinguishable at all.

**Precedent — the same conflation antipattern, accepted twice:**
- **#638** — *"Kiro CLI setup gate hijacks the whole app on a transient network failure."* Its argument: the gate "conflates two categorically different conditions", and a failed fetch "carries *zero* information about" whether Kiro CLI is set up. Identical shape here.
- **#613** (superseded by **#686**, merged) — *"treat macOS nesting EPERM as nesting, not a missing backend."* It objected to reporting "No OS-level sandbox backend is available on this host" — "a claim that is false on a host whose `sandbox-exec` works perfectly unnested." Same misdiagnosis class, fixed only for macOS nesting; this is the Linux host-level equivalent.

**Fix.**

`sandbox.py` gains `sandbox_unavailable_reason() -> tuple[str, str] | None`, a public seam so callers can classify the host without reaching into `_last_unshare_failure`. It returns `(kind, detail)`:

- `kind` is **machine-readable** — `transient` / `foreign_sandbox` / `no_backend` — so the presentation layer selects its own **translated** remedy copy instead of parsing English prose out of the API.
- `detail` is the technical probe reason, which since #1138 **names the failing step** (`unshare(CLONE_NEWNS) failed with errno 1 (EPERM)`), so it is surfaced verbatim and deliberately untranslated.

It is documented off-loop-only and called through `asyncio.to_thread`, because `detect_backend()` may fork a probe and the never-block-on-loop invariant would otherwise report a spurious `transient`.

`_probe` consults it **only when the first candidate is present and executable** (via the existing `_is_runnable_executable`, which stats rather than executes), then reports `installed=True`, `ready=False`, `sandbox_unavailable=True`. It offers **neither** install nor sign-in, because neither can fix a missing backend — a button that cannot help is the dead-end this removes. The genuine missing-binary path is untouched, and the new state cannot fire merely because a probe failed.

The gate renders a distinct screen naming the mechanism, with the probe detail in a `<pre>` and a single Check again action. Placement is deliberate: **after** `ready` and `initial_setup_complete`, so an established install is never hijacked by a full-screen gate — that was precisely #638's objection — and keeps surfacing the failure per-turn in context, which is specific now that the probe names the step. This branch only replaces the first-run screen that would otherwise lie. That limitation is intentional and worth a follow-up conversation rather than a silent expansion of scope here.

**Non-goals honored:** no fallback to unsandboxed execution (the `backend == "none"` branch stays fail-closed per #27, and `sandbox_allow_unsandboxed_exec` keeps its default); `_UNVERIFIED_SANDBOX_MODE` stays `"strict"` — verifying an untrusted binary under the strictest available confinement is correct, the bug was the *reporting*; nothing keys on `/etc/os-release` or distro ID.

The non-owner payload keeps the new fields **redacted but present**: the failure kind and probe detail describe host state (kernel knobs, errnos), which is exactly what that block already withholds, while a stable shape keeps the TypeScript type honest for every caller.

Also fixes a latent flake introduced with the probe rewrite in #1138: the fd-leak assertion counted `/proc/self/fd`, which races the background warm thread's own probe (it reproduced deterministically once these suites ran in the same process). It now tracks the calling thread's `pipe`/`close` calls.

## Related Issues

Part of #1139 (part 1 of 2 — the AppArmor remediation is not in this PR). Builds on #1137 / #1138. Same class as #638 and #613/#686.

## Testing

- [x] Existing tests pass (`make test`)
- [x] New tests added for new functionality
- [x] Manual verification performed (describe below if applicable)

**Backend** — 5 new tests in `test/test_kiro_prerequisite.py`: a present binary on a sandbox-less host reports `installed=True` + `sandbox_unavailable` and offers no install/sign-in; a genuinely missing binary still reports `installed=False`; a present binary whose `--version` merely fails on a *healthy* host is **not** misattributed to the sandbox (over-claim guard); a transient failure is reported as `transient`, not a host verdict; the healthy path leaves every new field at its default.

**Frontend** — 5 new cases in `KiroPrerequisiteGate.test.tsx` (29 total in file, all passing): the new screen renders with the mechanism copy and the verbatim probe detail, and offers no Install/Sign-in dead ends; a transient failure renders retry-oriented copy and *not* the host-verdict copy; `ready` takes precedence and never withholds the dashboard; an established install is not hijacked.

**Gates.** `flake8` and `mypy src/kiro_crew` clean. `tsc -b` clean (the real typecheck — `npm run typecheck` is a no-op here). `eslint .` → **0 errors, 312 warnings, byte-identical to pristine `main`**. Frontend suite: 578/579 files pass. Full `src/i18n` suite: 468 passing, including `catalogParity`, `untranslatedRatchet`, `deadKeys` and every locale style gate. `npm run i18n:check` passes end to end (`OK: 1349 untranslated strings ... at or below the baseline`).

**i18n.** Six new strings. They are `i18nT` fallbacks with no JSX literal to extract, so they live in `en.manual.json` where the codemod's regeneration of `en.json` cannot drop them, and are **genuinely translated into all nine target catalogs** — English passthrough is a designed runtime fallback but not a committable state (`catalogParity.test.ts`, and `TRANSLATION-PROMPT.md`: *"Never return the English string unchanged as a way of skipping a key"*). `en-XA.json` regenerated (5709 keys). The Hindi copy uses the informal register `style/hi.md` §4 requires — the first draft tripped the `आप` ratchet and was corrected rather than baselined upward.

**Backend suite baseline.** 23767 passed, 32 failed — **all 32 pre-existing on pristine `main` at `79c351bf`, zero new.** Worth flagging separately: 20 of those are `test/test_mcp_gateway_shutdown_and_env.py` failing on main with `TypeError: PoolKey.__init__() got an unexpected keyword argument 'channel_id'`, which reproduces on a clean checkout and looks like a semantic conflict between two independently-green PRs rather than anything environmental. Not caused by this branch, but `main` appears red.

No screenshots: I could not exercise this surface end-to-end against a live gateway on an affected host from here, so rather than stage a screenshot that misrepresents the render, the visual contract is pinned by the component tests above. Happy to add captures if a maintainer wants them before merge.

## Checklist

- [x] Code follows the project style guidelines
- [x] Self-review completed
- [x] Documentation updated (if applicable)
- [x] No secrets, credentials, or internal references in the diff

## Contribution License Agreement

By submitting this pull request I confirm that my contribution is made under the terms of the project's license.

### CODE REVIEW

**Comment by darko-mesaros** [comment]
Dispositions for `c8b16439`, now superseded by `33faff0c` (also rebased onto `4bd0c579`).

| review | finding | disposition |
|---|---|---|
| **Design (CONCERNS)** | Windows misattribution — the branch inferred "the sandbox caused this" from host state, never from the failed probe; on Windows verification runs **unsandboxed** yet `detect_backend()` returns `"none"` with detail `not Linux`, so a present-but-broken CLI would be blamed on the sandbox and lose its repair actions | **fixed, and it was right** |
| **Design (CONCERNS)** | "the description names the real root cause itself … and then the fix still doesn't read it" | **fixed** — the fix now keys on the actual failure |
| **UX (CONCERNS)** | Aside contradicts the headline (`SetupShell` still said "Install Kiro CLI, sign in once…") | **fixed** |
| **UX (CONCERNS)** | `no_backend` / `foreign_sandbox` are retry dead ends with no actionable remedy | **partially addressed — see below** |
| **UX (suggestion)** | drop "and was not cached" from the transient copy | **fixed** |
| **UX (suggestion)** | transient should not use alarm red | **fixed** |
| **GPT 5.6** | no blocking findings | — |

**The Design finding was a genuine regression and the more important half of this review.** Diagnosing from host capability is wrong on two supported configurations, not just Windows: `_run_process` skips the wrap on Windows (`if sandboxed and not platform_compat.IS_WINDOWS`), and `sandbox_allow_unsandboxed_exec` bypasses it on Linux — yet `detect_backend()` reports `"none"` in both. The reviewer also correctly noted my own description named the discarded signal (`ProcessResult.error`) and then failed to use it.

`wrap_argv` now raises a typed `SandboxUnavailableError(RuntimeError)` carrying `kind` + `detail`; `_run_process` records it on `ProcessResult.sandbox_failure`; `_probe` keys on **that**. Matching prose was rejected as brittle, hence a typed exception rather than a string check. It subclasses `RuntimeError` so existing handlers are untouched.

That single change also resolved the CI failures on the previous SHA, which had the same root cause: three pre-existing tests (`test_broken_linux_target_requires_manual_repair`, `test_installer_refuses_unchanged_existing_target`, `test_version_probe_failure_degrades_to_not_installed`) use stub runners returning `ok=False`, and on a GitHub runner — which **does** have `apparmor_restrict_unprivileged_userns=1` — my host-state check misattributed them. A stub runner cannot produce a `sandbox_failure`, so the coupling is gone structurally rather than by patching those tests. The over-claim guard test was rewritten to assert exactly this and renamed `test_probe_failure_unrelated_to_the_sandbox_is_not_misattributed`.

**On the remaining UX point:** I have deliberately not invented remedy copy for `no_backend` yet. The only remedies that exist today are the kernel-wide sysctl rollback and disabling the sandbox, and pointing a user at either would trade a real protection for an app-scoped need. The sanctioned per-application AppArmor profile is #1139 part 2, which I am building next; the remedy line should land with it and point at `kirocrew service install`. Shipping advice now that I would immediately have to rewrite seemed worse than shipping an honest "here is exactly what failed" screen. Happy to be overruled.

**Also, unrelated to this PR but worth flagging:** `main` was red for ~2h. #1081 added `channel_id=None` to `test_mcp_gateway_shutdown_and_env.py`'s `_pool_key()` helper, then #1191 (~1–2 min later) dropped that field from `PoolKey` and updated four other test files but missed this one. Each was green in its own CI because #1191 was tested against a base predating #1081 — a two-sided semantic conflict that no pre-merge check could catch. Already fixed upstream by #1201; this branch is rebased past it. Verified by bisect: 44 pass at `9767961d`, 20 fail at `195e1b00`.

Verification on this revision: `flake8` + `mypy` clean, `tsc -b` clean, `eslint .` at 0 errors (identical to pristine `main`), 468 i18n/gate frontend tests pass, `i18n:check` green, backend 23776 passed with 12 failures all pre-existing on `main`.

**Comment by darko-mesaros** [comment]
Disposition for `33faff0c`, superseded by `317fe43a`.

| finding | disposition | evidence |
|---|---|---|
| BLOCKING — `kiro_prerequisite.py:1967` `_is_runnable_executable` blocks the event loop; a stalled NFS/autofs candidate freezes the gateway | **fixed** | Legitimate. `_is_runnable_executable` → `_canonical_candidate` (`realpath`) → `platform_compat.is_executable_file` (`stat`), both synchronous, and a hung mount blocks them indefinitely. AUTOSDE's `no-blocking-call-on-event-loop` rule names exactly this class. Now `await asyncio.to_thread(_is_runnable_executable, ...)`, with the candidate emptiness check hoisted so the thread hop is skipped when there is no candidate. |

Worth noting the shape of this one: the branch it guards was *already* careful about the loop — the previous revision called `sandbox_unavailable_reason()` through `asyncio.to_thread` for the same reason. When that host probe was replaced with the typed-failure check, the thread hop went with it and the remaining synchronous filesystem call was left on the loop. So the regression came from removing the wrong thing along with the right thing.

`flake8`, `mypy` and all 135 `test_kiro_prerequisite.py` tests pass on `317fe43a`.

**Comment by darko-mesaros** [comment]
Rebased `317fe43a` -> `ceea4d2a` onto `2873d40f`. No code change.

`Frontend Lint & Type Check` failed on the previous SHA, and it was **base drift, not this diff**. ESLint itself passed (0 errors, 310 warnings). The failure came from the untranslated-string gate reporting regressions in two files this PR never touches:

```
pages/ChatSidebar.tsx: 33 → 34
pages/chat/AssistantMessage.tsx: 0 → 3
```

That gate measures **live against the base**, and `e42bcc5e` (#1047, "converge the hand-rolled formatters onto the seam") landed on `main` after this branch was cut and reduced the count in exactly those two files. The branch was carrying their older copies, so against the newer base it looked like a regression. Its own message says a baseline re-snapshot cannot clear it, which is correct — the only real fix is to rebase, not to touch the ledger. `website/AGENTS.md` documents this class of ratchet as breaking on unrelated drift in `main`.

After the rebase the gate passes: `OK: 1336 untranslated strings across 244 files, at or below the baseline of 1837`. Also re-verified on the new base: `tsc -b` clean, 486 frontend i18n/gate tests pass, `flake8` + `mypy` clean, 167 backend prerequisite/probe tests pass.

Worth noting for anyone hitting this later: because the comparison is live, any PR that sits through an i18n-touching merge on `main` will fail this gate until it rebases, regardless of what it changed.

**Review by iamwhatever — APPROVED** [review]
