### ISSUE TITLE
dashboard: consolidate the two JSON-object body-guard helpers, then sweep the ~85 unshaped request.json() handlers

### ISSUE THREAD

**Issue by chenmingwei23** [kirodotdev/KiroCrew#5587]
Follow-up from the First Principles review of PR #5575 (head 0d26e39da), which fixed the JSON-object body guard for the 9 `request.json()` sites in `knowledge.py` and deliberately deferred consolidation.

Two deferred items, in dependency order:

1. **Consolidate the two guard helpers into one owner.** `_shared.read_bounded_json` (5 call sites in 4 files) and `knowledge._json_object_body` (9 call sites) share the `invalid_json` / `body_not_object` codes and the `(body, err)` return contract but differ in: byte cap (required vs none), `allow_absent` (missing vs present), message text ("invalid JSON body" vs "invalid JSON"), and exception breadth (`Exception` vs `LookupError`+`ValueError` with transport errors propagating). Fold `allow_absent` and the narrowed exception semantics into `read_bounded_json`, settle the cap question for unbounded-body endpoints (import_bundle has no principled ceiling today), then delete `_json_object_body` -- one guard, one contract, 14 call sites.

2. **Sweep the sibling handlers.** The root cause (`.get()` on unshaped `request.json()`) is repo-wide: ~155 `await request.json()` sites across ~39 handler files; the bare `except Exception -> "invalid JSON"` guard without a dict check appears ~85 times in ~23 files (e.g. `memory.py`, `agents.py`, `taskrunner.py`; `cron.py` hand-rolls the isinstance check twice). Each such site 500s on a valid-JSON-non-object body. Route them through the consolidated helper from item 1.

Item 2 should not start before item 1 lands, or the sweep multiplies the second spelling.

Kiro Crew Auto-Pipeline [operator: chenmingwei23]

**Comment by dwu96** [comment]
🤖 Kiro Crew Auto-Pipeline [operator: dwu96#8c08bee0]: Routed to `needs-investigation` — the root cause is clear but the fix is gated on an open PR and on a decision the automation should not make for you.

**Why not auto-fixable.** Item 1 consolidates `knowledge._json_object_body` into `_shared.read_bounded_json`, but `_json_object_body` does not exist on main (`f0eabfb3`) — it arrives with PR #5575, which is still open. Consolidating a helper that is not yet on the branch point is not mechanically derivable. Item 1 also asks to "settle the cap question for unbounded-body endpoints (`import_bundle` has no principled ceiling today)": choosing a byte ceiling for a bundle-import endpoint is a design call with a real failure mode on both sides (too low silently breaks large legitimate bundles, absent leaves a memory-pressure surface), and the two helpers additionally disagree on exception breadth — `Exception` vs `LookupError`+`ValueError` with transport errors propagating — so folding them means deciding which transport-error behavior is correct, not just deleting a duplicate.

**What a human should decide.** (a) the `import_bundle` cap — a number, or an explicit "unbounded is correct here and the helper takes `max_bytes=None`"; (b) which exception contract wins, given that swallowing transport errors as `invalid_json` hides client disconnects; (c) the single message text, since both spellings are already in shipped responses.

**Sequencing is right as written.** Item 2 (the ~85 unshaped `except Exception -> "invalid JSON"` guards in ~23 files, plus the two hand-rolled isinstance checks in `cron.py`) must not start before item 1 lands, or the sweep bakes in the second spelling ~85 times. Once #5575 merges and (a)-(c) are answered, item 2 is a good mechanical candidate and can come back to this pipeline as its own issue.

Recorded for event-driven re-check when PR #5575 merges.

**Comment by chenmingwei23** [comment]
Kiro Crew Auto-Pipeline [operator: chenmingwei23#de330d0c]: Re-triage pass - stays needs-investigation. Item 1 (fold _json_object_body into _shared.read_bounded_json, 14 call sites) is largely mechanical, but it is gated on a real design decision the issue names: settling the byte-cap question for unbounded-body endpoints like import_bundle. Item 2 is a repo-wide ~85-site sweep that must not start before item 1 lands. The cap decision keeps this in needs-investigation.

**Comment by chenmingwei23** [comment]
Worklist addition from the First Principles review of PR #7012 (which lands item
1 and a first tranche of item 2). The sweep's scope as this issue originally
wrote it -- the ~85 unshaped `await request.json()` sites -- misses four guard
HELPERS that survive inside `src/kiro_crew/dashboard/` and do the same job with
divergent contracts. The issue's own sequencing argument applies to them: the
sweep must not finish while four contracts still diverge, or the divergence is
what gets baked in.

| helper | divergence | action |
|---|---|---|
| `handlers_channel.py:80 _json_object` | emits the IDENTICAL `invalid_json` / `body_not_object` codes, but raises `HTTPBadRequest` rather than returning `(None, response)`; prose is `request body must be a JSON object` vs `body must be a JSON object` | fold onto `read_bounded_json`; the codes already match, only the delivery style differs |
| `handlers/hooks.py:550 _json_object` | `except Exception: return {} if default_empty else None` -- a MALFORMED body collapses to defaults. **This is a live defect**, the exact one PR #7012 fixed at `POST /api/memory/promote`, and the helper's own docstring claims it "still rejects a body the caller clearly meant as data but shaped wrongly", which is true for a non-dict and false for malformed bytes | fix: distinguish absent from malformed, as `read_bounded_json(allow_absent=True)` does |
| `handlers/session_storage.py:158 _json_body` | deliberately different and documented (an empty body is legitimate on that surface, and a parse failure must not become `{}`). Gap: catches only `(ValueError, UnicodeDecodeError)`, so `LookupError` (unknown `charset=`) and `RecursionError` escape as 500; hardcodes utf-8 instead of honouring the declared charset | keep the contract, widen the catch |
| `handlers/artifacts.py:150 _read_json_body` | different contract (raises `ArtifactValidationError`), own cap reusing the `_MAX_BODY_BYTES` name, catches only `json.JSONDecodeError` | decide: adopt the shared guard, or document the divergence |

`hooks._json_object` is the one worth doing first -- it is a reachable bug, not a
consistency cleanup.

Note this is the dashboard tree only. The same root cause outside it
(`deploy/handlers.py` plus seven `apps/builtins/` spellings) is tracked
separately on #7028.

For the record, PR #7012's cap decisions are now enforced rather than
documented: `_CAP_REGISTER` in `test/test_json_object_body_guard.py` records
every `read_bounded_json` call site's cap choice with a reason, checked against
an AST scan, so a conversion in a later tranche cannot inherit `max_bytes=None`
without stating why.

**Comment by chenmingwei23** [comment]
One more decision the sweep has to settle FIRST, raised by the Design review of
PR #7012: the **return-shape axis**. This issue's own sequencing argument
("sweeping while two spellings exist bakes the second one in") applies to it, and
getting it wrong churns every converted site twice.

Two shapes exist today:

```python
# A. tuple -- _shared.read_bounded_json, 29 call sites
body, err = await read_bounded_json(request, max_bytes=None)
if err is not None:
    return err
assert body is not None  # for the type checker
...

# B. raise -- handlers_channel._json_object, hooks._json_object (variant)
body = await _json_object(request)   # raises HTTPBadRequest on a bad body
```

Evidence for the choice, so the sweep starts from a comparison rather than a
preference:

- **B is 1 line per site against A's 4.** Over ~65 sites that is a real
  difference and the honest argument in B's favour.
- **B routes an error through exception control flow.** `HTTPBadRequest` is both
  an exception and a Response, so any intermediate `except Exception` in a
  handler swallows or mangles it. Several dashboard handlers have exactly such a
  catch around their body-handling block.
- **B has no single prose owner.** `handlers_channel._json_object` hand-writes
  its JSON body as a text literal, which is precisely how its message drifted to
  `request body must be a JSON object` while the shared helper says
  `body must be a JSON object`. A raise-based form only avoids that if the shared
  helper builds the response, at which point the helper is back to producing a
  Response object anyway.
- **A's verbosity is mostly the `assert`.** That line exists for the type
  checker, not for runtime behaviour. A shape that returns a non-optional dict
  and signals failure separately would cut A to 3 lines without adopting B's
  exception control flow -- worth considering before committing to 65 copies of
  either.

Recommendation: settle on A (or the 3-line variant) and convert
`handlers_channel._json_object` to it as part of the four-sibling item above,
BEFORE the ~65-site sweep starts. Do not leave the axis open while sweeping.

**Comment by CrysisDeu** [comment]
🤖 Kiro Crew Auto-Pipeline [operator: CrysisDeu#0c98c3a2]: Re-triage promotion (partial scope). Item 1 (helper consolidation) already landed on main: read_bounded_json in dashboard/handlers/_shared.py settles every design question this issue was parked on — 64KB default cap with explicit max_bytes=None opt-out for unbounded-body endpoints, allow_absent folded in, narrowed exception contract, single 'invalid JSON' message. What remains mechanical is the sweep: ~190 bare await request.json() sites across ~40 dashboard handler files whose .get() on unshaped bodies turns valid-JSON-non-object requests into 500s; the conversion recipe is in the helper's own docstring. Fix PRs will use Refs #5587 and convert in per-file batches — the issue stays open until the sweep completes and a human decides the four surviving divergent guards (handlers_channel._json_object, hooks._json_object, artifacts._read_json_body, session_storage._json_body) and whether any max_bytes=None endpoint later gets a real ceiling. Starting an automated fix — this issue is now claimed by CrysisDeu#0c98c3a2's instance.

**Comment by CrysisDeu** [comment]
🤖 Kiro Crew Auto-Pipeline [operator: CrysisDeu#0c98c3a2]

Tranche 3 is up: https://github.com/kirodotdev/KiroCrew/pull/7308

Converts the 55 bare `await request.json()` sites in `chat_handlers.py` and `handlers/{mcp,cron,workflows,files}.py` onto `read_bounded_json`, with every cap decision recorded in the guard test's register (38 default-capped, 3 explicit per-route ceilings, 14 explicit `max_bytes=None`; the pending-cap ratchet stays at 13). Partial fix — this PR uses Refs and leaves the issue open: ~131 sites across ~51 files remain (largest: `handlers/messaging.py` with 27), plus the four divergent-guard fold decisions, which stay with a human.

**Comment by CrysisDeu** [comment]
🤖 Kiro Crew Auto-Pipeline [operator: CrysisDeu#0c98c3a2]

Tranche 3 is review-ready: https://github.com/kirodotdev/KiroCrew/pull/7308 — all 65 checks green (zero failures), PR Readiness passed, MERGEABLE. Human approval is the only remainder.

Head `6fe3b6d5b`, single commit. Three fix rounds during babysit, none touching the sweep's logic: a black-formatting graduation, a coverage-baseline prune (our tests pushed `handlers/cron.py` past the 80% per-file floor, so the shrink-only ratchet required its entry removed), and one runner-cancelled test shard rerun. After merge, #5587 stays open for the remaining ~131 sites (~51 files, largest `handlers/messaging.py` with 27) and the four divergent-guard fold decisions.

**Comment by CrysisDeu** [comment]
🤖 Kiro Crew Auto-Pipeline [operator: CrysisDeu#0c98c3a2]

Tranche 3 (PR #7308) is **review-ready again**: all 60 checks green, all AI review lanes PASS, MERGEABLE, single commit `0a11a85`. Only human approval remains.

Recovery path since the last review-ready state (2026-08-31):
- main advanced 468+ commits and the PR went CONFLICTING → rebased twice (onto `7853e8b05`, resolving 3-file conflicts with main's new `_is_valid_mcp_name` guard and `_audit_file_send` helper, then onto `2b1654d73` after #8317 fixed the main-inherited `test_autonudge_stop_auth.py` red).
- GPT round-2 blocking fixed: the `/interrupt` body-read rollback is now conditional on `_stop_state` still being `"soft_pending"`, so a concurrent hard-stop escalation is never erased (pinning test added). GPT advisory also fixed: `_MAX_CRON_BODY_BYTES` sized for JSON-escaped surrogate pairs (12 bytes/char).
- Final blocker was 10 consecutive `npm audit` 120s registry timeouts on the audit gate; resolved by rebasing onto main `e786b086d` (#8362 moved the audit gate to releases-only with transient retry).

No dependency, scope, or cap-register changes beyond the above; the 55-site `read_bounded_json` sweep content is unchanged.

**Comment by Pearcekieser** [comment]
Regression from the tranche-3 bounded-JSON migration in #7308 (`9d3d279ac`): `test/test_slot_close_recreation_race.py::_Req` invokes `api_chat_slots_cleanup` directly but does not define aiohttp's `can_read_body`. `read_bounded_json(..., allow_absent=True)` now reads that attribute before calling `json()`, so Windows shard 4 on PR #7509 fails five race tests; the exact test also fails locally on Linux.

Repro:
```bash
python3 -m pytest test/test_slot_close_recreation_race.py::test_cleanup_ordinary_archive_still_saves_and_removes -q -o addopts= -p no:cacheprovider
```

Observed error: `AttributeError: '_Req' object has no attribute 'can_read_body'` at `handlers/_shared.py:142`. Latest `main` (`701f8f981`) still reproduces. The fixture should model body presence, e.g. set `self.can_read_body = body is not None` before assigning `_body`; requests using the default absent body then follow the intended `allow_absent` path, while explicit bodies remain readable.

**Comment by Pearcekieser** [comment]
Additional current-main evidence from PR #7509: `Backend Tests (3.12, 4)` now failed too, not only Windows shard 4. It reports the same `_Req.can_read_body` `AttributeError`; the race tests that schedule the handler and then wait for an internal event subsequently time out at 120s because the handler exits before signaling that event. This confirms a cross-platform deterministic gate break, not a Windows runner flake.

**Comment by bolichen97** [comment]
Closing: the shipped half is on `main`, and the remainder has moved to
#12257 so it can be seen next to the other items in the same area.

**Shipped:** the helper consolidation plus three sweep tranches in #7012, #7170 and #7308.

**Moved to #12257:** the four deliberately-divergent guards (`handlers_channel`, `hooks.py`, `artifacts.py`, `session_storage.py`) and the return-shape axis decision.

Nothing is dropped and nothing is judged done that is not. The reason for moving
rather than leaving this open: a one-line remainder on a mostly-delivered issue
reads as finished to anyone skimming it, so the part that is not done stops being
picked up. Full context, measurements and the original discussion stay here and
are linked from #12257.

Reopen this instead if folding it was the wrong call.

<sub>Issue sweep: 72 partially-delivered issues read against `main`; this one's
remainder was consolidated.</sub>
