### ISSUE TITLE
ci: main fails pytest collection (missing patch_private_memory_supported), failing every test shard on every PR

### ISSUE THREAD

**Issue by chenmingwei23** [kirodotdev/KiroCrew#12082]
## Summary

`main` fails pytest COLLECTION, so every test shard on every PR fails regardless of
its own content. `test/test_member_memory_runtime.py` imports a helper that
`test/member_memory_helpers.py` does not define:

```
ImportError: cannot import name 'patch_private_memory_supported' from 'member_memory_helpers'
```

A collection error interrupts the whole pytest session (`Interrupted: 1 error
during collection`), so the failure is not confined to that module.

## Reproduction

On a pristine detached worktree at `origin/main` with no local modifications:

```
git worktree add --detach <dir> origin/main
KIROCREW_HOME=<scratch> PYTHONPATH=<dir>/src python3 -m pytest --collect-only -q -n0
```

```
ERROR test/test_member_memory_runtime.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
118021 tests collected, 1 error
```

## Which commit, and the evidence

`1c7f963706` ("fix: resolve private store from binding when transcript lags
(#11947)") added the uses without the definition. Counting both sides across the
two commits that touched these files:

| commit | `def patch_private_memory_supported` in helpers | uses in `test_member_memory_runtime.py` |
|---|---|---|
| `bc0d2b0cfc` (`refactor(memory): simplify member memory to one SQLite store`) | 0 | 0 |
| `1c7f963706` (current tip) | 0 | 3 |

So the refactor removed or never added the helper, and the follow-up started
calling it.

## Blast radius

Because collection is interrupted, the lanes that fail are every lane that runs
the suite. Observed on an unrelated PR whose own tests pass in isolation:
`Backend Tests (3.12, 1-8)`, `Backend Tests (Windows) (1-8)`,
`Windows Fail-Closed Sandbox Contract`, `Real Adapter Contract Tests`,
`E2E (stub ACP backend, offline)`, `E2E Gateway Boot (ubuntu-latest)`,
`E2E Gateway Boot (windows-latest)`, `Coverage Gate`, and `PR Readiness`
aggregating them.

These lanes are `pull_request`-triggered, so `main`'s own check runs do NOT cover
them. `main` looks green while every PR built on it is red, which is what makes
this easy to mis-attribute to the PR under review. I initially mis-attributed it
that way myself before checking a pristine `main`.

## Suggested fix

Either define `patch_private_memory_supported` in `test/member_memory_helpers.py`,
or change the three call sites in `test/test_member_memory_runtime.py` to whatever
replaced it in the SQLite-store refactor. I have not guessed which is intended, so
this is filed rather than patched.

Filed from PR #12046, which is blocked on it.

**Comment by helenastafford** [comment]
The same `bc0d2b0cf` x #11947 collision breaks a **second symbol, in src this time**, so the blast radius goes beyond pytest collection: runtime failures in lanes that never import the test helpers.

`src/kiro_crew/context.py:247` (added by #11947) imports and calls `require_private_memory_execution` from `kiro_crew.member_memory_auth` — but `bc0d2b0cf` deleted that function (and its `private_memory_execution_supported` helper chain). On current tip `1c7f96370`:

```
$ git grep -n "require_private_memory_execution" origin/main -- src/
src/kiro_crew/context.py:247:        from kiro_crew.member_memory_auth import require_private_memory_execution
src/kiro_crew/context.py:249:        await asyncio.to_thread(require_private_memory_execution, session_key=session_key)
$ git grep -n "def require_private_memory_execution" origin/main -- '*.py'
(no matches)
```

Observed downstream on PR merge refs (kirodotdev/KiroCrew#9969, which touches neither file):

- **CI / E2E (stub ACP backend, offline)**: `test/e2e/test_private_workflow_memory.py::test_private_workflows_execute_over_real_projected_mcp` — slot error `cannot import name 'require_private_memory_execution' from 'kiro_crew.member_memory_auth'`
- **CI / Windows Fail-Closed Sandbox Contract**: `test_health_then_one_session_and_one_prompt_succeed` — no assistant reply within 180s (the same ImportError surfacing as a dead provider spawn, indistinguishable from a fail-closed spawn from the outside)

Notably, #11947's `context.py` diff is revert-shaped relative to the refactor: it restores the pre-`bc0d2b0cf` block verbatim (including the old comment wording) and drops the refactor's `execution_context` gate — consistent with being developed on a pre-refactor base and merged without rebase. A fix that only re-adds the two missing test helpers would still leave this src-side ImportError; reconciling #11947 with the refactor (or reverting it) looks like the actual fix, which is the feature owners' call.

**Comment by helenastafford** [comment]
Additional evidence — the same collision breaks a **second** symbol: `member_for_store` is imported from `kiro_crew.member_essential_context` but no longer defined there (also deleted by the `bc0d2b0cf` memory refactor, re-referenced by #11947's stale-base diff).

Blast radius on pristine main tip `1c7f96370` (local probe): `test/test_channel_history.py` fails 3 tests with the ImportError, and `test/test_auto_approve.py` fails 6 assertions in the same run (9 failed / 45 passed on just those two files). On PR merge refs this now reds backend shards on both platforms plus both E2E Gateway Boot jobs, the stub E2E, and the Windows Fail-Closed Sandbox Contract — every open PR inherits it.

Both symbols need reconciling in the same fix: `require_private_memory_execution` (src/kiro_crew/context.py) and `member_for_store`.

**Comment by helenastafford** [comment]
Complete inventory of the breakage, from CI's `Backend Lint & Type Check (3.12)` (mypy over main tip `1c7f96370` — now failing on every PR's merge ref):

```
src/kiro_crew/context.py:247:  Module "kiro_crew.member_memory_auth" has no attribute "require_private_memory_execution"
src/kiro_crew/context.py:433:  Module "kiro_crew.config.paths" has no attribute "private_runtime_log_dir"
src/kiro_crew/context.py:3438: Module "kiro_crew.member_essential_context" has no attribute "member_for_store"
src/kiro_crew/context.py:4302: Module "kiro_crew.member_essential_context" has no attribute "member_for_store"
src/kiro_crew/dashboard/state.py:4446: "ContextBuilder" has no attribute "live_memory_mode_for_session"; maybe "memory_mode_for_session"?
```

So the stale-base surface is **four symbols across three modules**, not two — plus a runtime signature mismatch that mypy can't see statically but which kills every E2E turn:

```
TypeError: ContextBuilder.build_message() got an unexpected keyword argument 'execution_context'
```

(visible in the `E2E Gateway Boot` job logs — the slot errors out on the first prompt, so gateway-boot, stub-E2E, and the Windows fail-closed contract all time out waiting for an assistant reply).

Whoever reconciles #11947 with the `bc0d2b0cf` refactor: the mypy list above plus the `build_message` call-site signature should be the checklist for a complete fix.

**Comment by CrysisDeu** [comment]
🤖 Kiro Crew Auto-Pipeline [operator: CrysisDeu#0c98c3a2]: Possibly covered by open PR #12085 (a clean `git revert` of `1c7f96370` / #11947, opened 20:24Z). It restores the pre-#11947 `context.py`, `state.py` and the three test files, so both the collection-time helper imports (#12082) and the call-time `member_memory_auth` / `member_essential_context` / `config.paths` imports (#12083) disappear together. Leaving this open until that PR (or a reconcile) merges; the PR carries no closing reference, so it will not auto-close this issue.

**Comment by bolichen97** [comment]
Fixed on `main`, so closing. The breakage came from two PRs written against the pre-#11780 member-memory model that merged after [PR #11780](https://github.com/kirodotdev/KiroCrew/pull/11780) removed it, with a textually clean merge: [#11947](https://github.com/kirodotdev/KiroCrew/pull/11947) (the `context.py` / `test_member_memory_runtime.py` references) and [#11960](https://github.com/kirodotdev/KiroCrew/pull/11960) (`test_subagent_continuable.py`). Both are reverted: [PR #12091](https://github.com/kirodotdev/KiroCrew/pull/12091) (`39892f5c1`) and [PR #12088](https://github.com/kirodotdev/KiroCrew/pull/12088) (`ddea8d79f`). A grep of `src/` and `test/` on current `main` for every symbol #11780 deleted returns no references.

The other open PRs carrying the same hazard have been commented on and, where GitHub still reports them mergeable, blocked with Request Changes until they rebase.
