### PR TITLE
test: drop the removed private-memory gate patches reintroduced by #11947/#11960

### LINKED ISSUE #12082: ci: main fails pytest collection (missing patch_private_memory_supported), failing every test shard on every PR
## Summary

`main` fails pytest COLLECTION, so every test shard on every PR fails regardless of
its own content. `test/test_member_memory_runtime.py` imports a helper that
`test/member_memory_helpers.py` does not define:

```
ImportError: cannot import name 'patch_private_memory_supported' from 'member_memory_helpers'
```

A collection error interrupts the whole pytest session (`Interrupted: 1 error
during collection`), so the failure is not confined to that module.

## Reproduction

On a pristine detached worktree at `origin/main` with no local modifications:

```
git worktree add --detach <dir> origin/main
KIROCREW_HOME=<scratch> PYTHONPATH=<dir>/src python3 -m pytest --collect-only -q -n0
```

```
ERROR test/test_member_memory_runtime.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
118021 tests collected, 1 error
```

## Which commit, and the evidence

`1c7f963706` ("fix: resolve private store from binding when transcript lags
(#11947)") added the uses without the definition. Counting both sides across the
two commits that touched these files:

| commit | `def patch_private_memory_supported` in helpers | uses in `test_member_memory_runtime.py` |
|---|---|---|
| `bc0d2b0cfc` (`refactor(memory): simplify member memory to one SQLite store`) | 0 | 0 |
| `1c7f963706` (current tip) | 0 | 3 |

So the refactor removed or never added the helper, and the follow-up started
calling it.

## Blast radius

Because collection is interrupted, the lanes that fail are every lane that runs
the suite. Observed on an unrelated PR whose own tests pass in isolation:
`Backend Tests (3.12, 1-8)`, `Backend Tests (Windows) (1-8)`,
`Windows Fail-Closed Sandbox Contract`, `Real Adapter Contract Tests`,
`E2E (stub ACP backend, offline)`, `E2E Gateway Boot (ubuntu-latest)`,
`E2E Gateway Boot (windows-latest)`, `Coverage Gate`, and `PR Readiness`
aggregating them.

These lanes are `pull_request`-triggered, so `main`'s own check runs do NOT cover
them. `main` looks green while every PR built on it is red, which is what makes
this easy to mis-attribute to the PR under review. I initially mis-attributed it
that way myself before checking a pristine `main`.

## Suggested fix

Either define `patch_private_memory_supported` in `test/member_memory_helpers.py`,
or change the three call sites in `test/test_member_memory_runtime.py` to whatever
replaced it in the SQLite-store refactor. I have not guessed which is intended, so
this is filed rather than patched.

Filed from PR #12046, which is blocked on it.

### PR DESCRIPTION
**Pull request by pepmach**
## Problem / Motivation

Main cannot collect the backend test suite. #11947 and #11960 restored test code from before #11780 removed the private-memory capability gate, including an import of `patch_private_memory_supported` that no longer exists.

## Why it matters

The collection error has made nine backend shards fail since 19:42 UTC. Run 35465194443 and every pull request merge ref inherit the failure, regardless of their own changes.

## What changed (motivation → approach → change)

This tests-only heal restores `test/test_member_memory_runtime.py` and `test/test_subagent_continuable.py` to #11780's execution-context model. It removes the missing helper import, its two calls, and both patches of the deleted `private_memory_execution_supported` gate.

The new behavior tests from #11947 and #11960 remain. They cover lagging transcript metadata, cross-store refusal, and shared-provider labels without restoring the deleted capability model.

## Backwards compatibility

Compatible: this changes tests only and does not alter product behavior.

## Tests

- `test/test_member_memory_runtime.py test/test_subagent_continuable.py -n0`: 279 collected, 257 passed, 22 failed only through #12083's untouched production imports. The failures name `require_private_memory_execution` at `src/kiro_crew/context.py:247` or `private_runtime_log_dir` at `src/kiro_crew/context.py:433`; no test was deleted or skipped for them.
- `scripts/check_black_formatting.py`: passed after commit.
- Black direct check, isort, flake8, comment-history, and `git diff --check`: passed.
- mypy: five inherited errors in unchanged source files, including both #12083 imports. This branch has no `src/kiro_crew` diff.

## Manual verification

N/A — the test collection result directly verifies #12082. Product execution remains owned by #12083.

## Related Issues

Fixes #12082

Related: #12083

## Pattern harvest

Rule candidate: review-prompt
Pattern: before merging work across a large refactor, compare every touched file with the current base; a conflict-free patch can restore deleted tests and APIs.

## Checklist

- [x] At most two commits (one is the norm), with a Conventional Commits title (`feat|fix|docs|refactor|perf|test|chore|ci|build|revert: ...`)
- [ ] Existing tests pass and new tests added for new functionality — blocked only by #12083's unchanged production errors
- [x] Self-review completed; code follows project style guidelines
- [x] Documentation updated (if applicable) — N/A, tests only
- [x] No secrets, credentials, or internal references in the diff

### CODE REVIEW

**Comment by pepmach** [comment]
**Intent:** Restore the two test files to the one-store execution-context model so pytest collection resumes, while preserving the new coverage from #11947 and #11960.
**Not a goal:** Decide or modify #12083 production behavior.

**Comment by pepmach** [comment]
Withdrawn: superseded by #12088 (Bolin's revert of both stale-base merges, #11960 and #11947), which removes every remaining reference to the deleted private-memory gate — including the two test_subagent_continuable.py monkeypatches this PR targeted — and restores the context.py imports (#12082, #12083).
